In [30]:
# =========================================================
# Cell 1. 기본 세팅
# =========================================================

# 처음 한 번만 필요할 수 있음
# !pip install pandas numpy statsmodels scikit-learn matplotlib openpyxl pyreadstat

import os
import re
import zipfile
import warnings
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.api as sm

warnings.filterwarnings("ignore")

pd.set_option("display.max_columns", 200)
pd.set_option("display.width", 260)
pd.set_option("display.float_format", lambda x: f"{x:,.5f}")

print("Setup complete.")

Setup complete.

In [31]:
# =========================================================
# Cell 2. 파일 경로 설정
# =========================================================

# 본인 컴퓨터 경로에 맞게 설정
base_dir = r"C:\Users\starw\OneDrive\바탕 화면\학교 생활\UNIST\Research\박지훈 자료"

file_paths = {
    # Compustat annual
    "funda": os.path.join(base_dir, "funda.sas7bdat"),

    # CRSP monthly stock file
    "msf": os.path.join(base_dir, "msf.sas7bdat"),

    # CRSP monthly event/security file
    "mseall": os.path.join(base_dir, "mseall.sas7bdat"),

    # New York Fed CRSP-FRB Link file
    # 교수님이 말한 PERMCO 기준 은행 식별용 파일
    "permco_bank_list": r"C:\Users\starw\OneDrive\바탕 화면\학교 생활\UNIST\Research\박지훈 자료\crsp_20240930v2.csv",
}

# 결과 저장 폴더
output_folder = os.path.join(base_dir, "permco_bank_analysis_output")
os.makedirs(output_folder, exist_ok=True)

for name, path in file_paths.items():
    if os.path.exists(path):
        size_mb = os.path.getsize(path) / (1024 ** 2)
        print(f"{name}: FOUND | {size_mb:,.2f} MB | {path}")
    else:
        print(f"{name}: NOT FOUND | {path}")

print("\nOutput folder:", output_folder)

funda: FOUND | 6,902.50 MB | C:\Users\starw\OneDrive\바탕 화면\학교 생활\UNIST\Research\박지훈 자료\funda.sas7bdat
msf: FOUND | 828.12 MB | C:\Users\starw\OneDrive\바탕 화면\학교 생활\UNIST\Research\박지훈 자료\msf.sas7bdat
mseall: FOUND | 1,436.00 MB | C:\Users\starw\OneDrive\바탕 화면\학교 생활\UNIST\Research\박지훈 자료\mseall.sas7bdat
permco_bank_list: FOUND | 0.11 MB | C:\Users\starw\OneDrive\바탕 화면\학교 생활\UNIST\Research\박지훈 자료\crsp_20240930v2.csv

Output folder: C:\Users\starw\OneDrive\바탕 화면\학교 생활\UNIST\Research\박지훈 자료\permco_bank_analysis_output

In [32]:
# =========================================================
# Cell 3. 공통 함수
# =========================================================

def read_sas_filtered(path, columns=None, chunksize=500_000, filter_func=None, encoding="latin1"):
    """
    대용량 sas7bdat 파일을 chunk 단위로 읽고,
    필요한 컬럼과 조건만 남기는 함수.
    """
    if not os.path.exists(path):
        raise FileNotFoundError(f"File not found: {path}")

    collected = []

    reader = pd.read_sas(
        path,
        format="sas7bdat",
        encoding=encoding,
        chunksize=chunksize
    )

    for i, chunk in enumerate(reader):
        print(f"Reading chunk {i+1}: {chunk.shape}")

        chunk.columns = [str(c) for c in chunk.columns]

        if columns is not None:
            existing_cols = [c for c in columns if c in chunk.columns]
            missing_cols = [c for c in columns if c not in chunk.columns]
            if i == 0 and len(missing_cols) > 0:
                print("Missing columns in this file:", missing_cols)
            chunk = chunk[existing_cols].copy()

        if filter_func is not None:
            chunk = filter_func(chunk)

        if len(chunk) > 0:
            collected.append(chunk)

    if len(collected) == 0:
        print("No rows matched the filter.")
        return pd.DataFrame()

    out = pd.concat(collected, ignore_index=True)
    print("Final loaded shape:", out.shape)
    return out


def safe_divide(a, b):
    return np.where((b == 0) | pd.isna(b), np.nan, a / b)


def compound_return(ret_series):
    r = pd.to_numeric(ret_series, errors="coerce").dropna()
    if len(r) == 0:
        return np.nan
    return np.prod(1 + r) - 1


def max_drawdown_from_returns(ret_series):
    r = pd.to_numeric(ret_series, errors="coerce").dropna()
    if len(r) == 0:
        return np.nan

    wealth = (1 + r).cumprod()
    running_max = wealth.cummax()
    drawdown = wealth / running_max - 1
    return drawdown.min()


def winsorize_series(s, lower=0.01, upper=0.99):
    s = pd.to_numeric(s, errors="coerce")
    if s.notna().sum() < 20:
        return s
    lo = s.quantile(lower)
    hi = s.quantile(upper)
    return s.clip(lo, hi)


def make_stars(p):
    if pd.isna(p):
        return ""
    if p < 0.01:
        return "***"
    elif p < 0.05:
        return "**"
    elif p < 0.10:
        return "*"
    else:
        return ""


def clean_permco(x):
    """
    PERMCO를 숫자형 정수로 정리.
    """
    return pd.to_numeric(x, errors="coerce").astype("Int64")


print("Common functions ready.")

Common functions ready.

In [33]:
# =========================================================
# Cell 4. New York Fed CRSP-FRB Link에서 은행 PERMCO 리스트 만들기
# =========================================================

def parse_yyyymmdd(x):
    """
    20240930 같은 YYYYMMDD 숫자/문자열을 datetime으로 변환.
    변환 불가능하면 NaT.
    """
    return pd.to_datetime(x.astype(str), format="%Y%m%d", errors="coerce")


def load_crsp_frb_permco_link(
    path,
    analysis_start="2021-01-01",
    analysis_end="2023-12-31",
    keep_only_bank_related_inst_types=False
):
    """
    New York Fed CRSP-FRB Link 파일에서 PERMCO 은행 리스트 생성.

    네 파일 구조:
    - name
    - inst_type
    - entity
    - permco
    - dt_start
    - dt_end

    기본 원칙:
    1. permco를 CRSP 회사 단위 은행 식별자로 사용
    2. dt_start, dt_end를 사용해 2021-2023 연구기간과 겹치는 link만 유지
    3. PERMCO 중복 제거
    """

    if not os.path.exists(path):
        raise FileNotFoundError(f"File not found: {path}")

    df = pd.read_csv(path)

    # 컬럼명 정리
    df.columns = [str(c).strip().lower() for c in df.columns]

    print("Raw CRSP-FRB Link shape:", df.shape)
    print("Columns:", df.columns.tolist())

    required_cols = ["name", "inst_type", "entity", "permco", "dt_start", "dt_end"]
    missing_cols = [c for c in required_cols if c not in df.columns]

    if len(missing_cols) > 0:
        raise ValueError(f"Missing required columns: {missing_cols}")

    # 기본 정리
    df["permco"] = pd.to_numeric(df["permco"], errors="coerce")
    df["entity"] = pd.to_numeric(df["entity"], errors="coerce")

    df = df.dropna(subset=["permco"]).copy()
    df["permco"] = df["permco"].astype(int)
    df["PERMCO"] = df["permco"]

    # 날짜 변환
    df["link_start"] = parse_yyyymmdd(df["dt_start"])
    df["link_end"] = parse_yyyymmdd(df["dt_end"])

    analysis_start = pd.Timestamp(analysis_start)
    analysis_end = pd.Timestamp(analysis_end)

    print("\nOriginal link date range:")
    print("link_start min:", df["link_start"].min())
    print("link_start max:", df["link_start"].max())
    print("link_end min:", df["link_end"].min())
    print("link_end max:", df["link_end"].max())

    print("\nInstitution type distribution, raw:")
    display(df["inst_type"].value_counts(dropna=False).reset_index().rename(
        columns={"index": "inst_type", "inst_type": "N"}
    ))

    # 선택 옵션: 명백한 은행 관련 inst_type만 유지
    # 기본값은 False. 교수님이 "링크에 있는 PERMCO"라고 했으므로 일단 전체 link 사용 권장.
    if keep_only_bank_related_inst_types:
        bank_keywords = [
            "bank",
            "thrift",
            "fsb",
            "national",
            "member"
        ]

        pattern = "|".join(bank_keywords)

        before = len(df)
        df = df[
            df["inst_type"]
            .astype(str)
            .str.lower()
            .str.contains(pattern, na=False)
        ].copy()

        print(f"\nFiltered to bank-related inst_type: {before:,} -> {len(df):,}")

    # 2021-2023 연구기간과 link 기간이 겹치는 PERMCO만 유지
    before = len(df)

    df_active = df[
        (df["link_start"].isna() | (df["link_start"] <= analysis_end)) &
        (df["link_end"].isna() | (df["link_end"] >= analysis_start))
    ].copy()

    print(f"\nApplied active-link filter for {analysis_start.date()} to {analysis_end.date()}:")
    print(f"{before:,} rows -> {len(df_active):,} rows")

    # PERMCO 중복 제거
    # 같은 PERMCO가 여러 entity/RSSD에 연결될 수 있으므로,
    # 연구기간과 겹치는 link 중 가장 최근까지 유효한 link를 대표로 선택.
    bank_permco_list = (
        df_active
        .sort_values(["permco", "link_end", "link_start"], ascending=[True, False, False])
        .drop_duplicates(subset=["permco"], keep="first")
        .copy()
    )

    print("\nUnique PERMCO count:")
    print("Raw file:", df["permco"].nunique())
    print("Active during analysis window:", df_active["permco"].nunique())
    print("After one-row-per-PERMCO:", bank_permco_list["PERMCO"].nunique())

    print("\nInstitution type distribution, active links:")
    display(df_active["inst_type"].value_counts(dropna=False).reset_index().rename(
        columns={"index": "inst_type", "inst_type": "N"}
    ))

    print("\nSample of final PERMCO bank list:")
    display(bank_permco_list.head(20))

    return bank_permco_list, df_active, df


# 실행
bank_permco_list_raw, bank_permco_link_filtered, bank_permco_link_all = load_crsp_frb_permco_link(
    file_paths["permco_bank_list"],
    analysis_start="2021-01-01",
    analysis_end="2023-12-31",
    keep_only_bank_related_inst_types=False
)

# 이후 셀에서 사용할 PERMCO 리스트
bank_permcos = sorted(
    bank_permco_list_raw["PERMCO"]
    .dropna()
    .astype(int)
    .unique()
    .tolist()
)

bank_permco_set = set(bank_permcos)

print("\nNumber of bank PERMCOs used in analysis:", len(bank_permcos))
print("First 20 PERMCOs:", bank_permcos[:20])

Raw CRSP-FRB Link shape: (1495, 6)
Columns: ['name', 'inst_type', 'entity', 'permco', 'dt_start', 'dt_end']

Original link date range:
link_start min: 1986-06-30 00:00:00
link_start max: 2024-07-12 00:00:00
link_end min: 1986-10-31 00:00:00
link_end max: 2024-09-30 00:00:00

Institution type distribution, raw:

                         N  count
0     Bank Holding Company   1213
1          Commercial Bank    127
2   Thrift holding company     83
3   Thrift Holding Company     40
4    Domestic Entity Other     11
5     Bank holding company     10
6          Non Member Bank      6
7                   Thrift      1
8                      NaN      1
9   Thirft Holding Company      1
10                     FSB      1
11                National      1

Applied active-link filter for 2021-01-01 to 2023-12-31:
1,495 rows -> 395 rows

Unique PERMCO count:
Raw file: 1450
Active during analysis window: 394
After one-row-per-PERMCO: 394

Institution type distribution, active links:

                         N  count
0     Bank Holding Company    320
1   Thrift Holding Company     32
2   Thrift holding company     24
3          Commercial Bank      6
4          Non Member Bank      5
5    Domestic Entity Other      2
6     Bank holding company      2
7                      NaN      1
8   Thirft Holding Company      1
9                      FSB      1
10                National      1

Sample of final PERMCO bank list:

                              name               inst_type   entity  permco  dt_start    dt_end  PERMCO link_start   link_end
1214           AMERICAN EXPRESS CO  Thrift Holding Company  1275216      90  19860630  20240930      90 1986-06-30 2024-09-30
1108  AMERICAN INTERNATIONAL GROUP  Thrift holding company  1562176     137  19860630  20240930     137 1986-06-30 2024-09-30
1215          ASSOCIATED BANC-CORP    Bank Holding Company  1199563     362  19860630  20240930     362 1986-06-30 2024-09-30
1109                 POPULAR, INC.    Bank Holding Company  1129382     475  19860630  20240930     475 1986-06-30 2024-09-30
1487                 NEWTEKONE INC    Bank Holding Company  5586741     579  20230106  20240930     579 2023-01-06 2024-09-30
1216           BANK OF HAWAII CORP    Bank Holding Company  1025309     589  19860630  20240930     589 1986-06-30 2024-09-30
1217       COMMERCE BANCSHARES INC    Bank Holding Company  1049341     779  19860630  20240930     779 1986-06-30 2024-09-30
1218        SYNOVUS FINANCIAL CORP    Bank Holding Company  1078846     781  19860630  20240930     781 1986-06-30 2024-09-30
1219      CULLEN/FROST BANKERS INC    Bank Holding Company  1102367     840  19860630  20240930     840 1986-06-30 2024-09-30
1220                  COMERICA INC    Bank Holding Company  1199844    1261  19860630  20240930    1261 1986-06-30 2024-09-30
1365        REGIONS FINANCIAL CORP    Bank Holding Company  3242838    1620  20040701  20240930    1620 2004-07-01 2024-09-30
1221                    US BANCORP    Bank Holding Company  1119794    1645  19860630  20240930    1645 1986-06-30 2024-09-30
1222                TRUSTMARK CORP    Bank Holding Company  1079562    1658  19860630  20240930    1658 1986-06-30 2024-09-30
1223               M & T BANK CORP    Bank Holding Company  1037003    1689  19860630  20240930    1689 1986-06-30 2024-09-30
1224           FIFTH THIRD BANCORP    Bank Holding Company  1070345    1741  19860630  20240930    1741 1986-06-30 2024-09-30
1225            FIRST HORIZON CORP    Bank Holding Company  1094640    1856  19860630  20240930    1856 1986-06-30 2024-09-30
1226          ARROW FINANCIAL CORP    Bank Holding Company  1048812    1940  19860630  20240930    1940 1986-06-30 2024-09-30
1227         HUNTINGTON BANCSHARES    Bank Holding Company  1068191    2093  19860630  20240930    2093 1986-06-30 2024-09-30
1228    WESTAMERICA BANCORPORATION    Bank Holding Company  1025541    2253  19860630  20240930    2253 1986-06-30 2024-09-30
1289                       KEYCORP    Bank Holding Company  1068025    2535  19940302  20240930    2535 1994-03-02 2024-09-30

Number of bank PERMCOs used in analysis: 394
First 20 PERMCOs: [90, 137, 362, 475, 579, 589, 779, 781, 840, 1261, 1620, 1645, 1658, 1689, 1741, 1856, 1940, 2093, 2253, 2535]

In [34]:
# =========================================================
# Cell 5. 분석 기간 설정
# =========================================================

# 메인 분석 기간
main_start = pd.Timestamp("2022-03-01")
main_end = pd.Timestamp("2023-03-31")

# 확장 분석 기간
extended_start = pd.Timestamp("2022-03-01")
extended_end = pd.Timestamp("2023-07-31")

# March 2023 stress window
march_start = pd.Timestamp("2023-03-01")
march_end = pd.Timestamp("2023-03-31")

# CRSP에서 읽을 전체 기간
shock_start = main_start
shock_end = extended_end

print("Main period:", main_start, "to", main_end)
print("Extended period:", extended_start, "to", extended_end)
print("March 2023:", march_start, "to", march_end)

Main period: 2022-03-01 00:00:00 to 2023-03-31 00:00:00
Extended period: 2022-03-01 00:00:00 to 2023-07-31 00:00:00
March 2023: 2023-03-01 00:00:00 to 2023-03-31 00:00:00

In [35]:
# =========================================================
# Cell 6. CRSP msf에서 PERMCO 은행 수익률 추출
# =========================================================

msf_cols = [
    "CUSIP", "PERMNO", "PERMCO", "DATE",
    "RET", "RETX", "PRC", "SHROUT", "VOL",
    "HSICCD", "HEXCD"
]

bank_permco_set = set(bank_permcos)

def filter_msf_permco_banks(chunk):
    chunk.columns = [str(c) for c in chunk.columns]

    chunk["DATE"] = pd.to_datetime(chunk["DATE"], errors="coerce")
    chunk["PERMCO"] = pd.to_numeric(chunk["PERMCO"], errors="coerce")

    chunk = chunk[
        (chunk["DATE"] >= shock_start) &
        (chunk["DATE"] <= shock_end) &
        (chunk["PERMCO"].isin(bank_permco_set))
    ].copy()

    return chunk


msf_bank_raw = read_sas_filtered(
    file_paths["msf"],
    columns=msf_cols,
    chunksize=500_000,
    filter_func=filter_msf_permco_banks
)

msf_bank = msf_bank_raw.copy()

if len(msf_bank) == 0:
    raise ValueError("No CRSP MSF rows matched the PERMCO bank list. PERMCO list or CRSP file should be checked.")

# 변수 정리
msf_bank["CUSIP"] = msf_bank["CUSIP"].astype(str).str[:8]
msf_bank["PERMNO"] = pd.to_numeric(msf_bank["PERMNO"], errors="coerce")
msf_bank["PERMCO"] = pd.to_numeric(msf_bank["PERMCO"], errors="coerce")
msf_bank["RET"] = pd.to_numeric(msf_bank["RET"], errors="coerce")
msf_bank["RETX"] = pd.to_numeric(msf_bank["RETX"], errors="coerce")
msf_bank["PRC"] = pd.to_numeric(msf_bank["PRC"], errors="coerce")
msf_bank["SHROUT"] = pd.to_numeric(msf_bank["SHROUT"], errors="coerce")
msf_bank["VOL"] = pd.to_numeric(msf_bank["VOL"], errors="coerce")

# CRSP PRC는 bid/ask average 표시 때문에 음수일 수 있으므로 시가총액 계산에는 절댓값 사용
msf_bank["abs_prc"] = msf_bank["PRC"].abs()
msf_bank["mktcap_crsp"] = msf_bank["abs_prc"] * msf_bank["SHROUT"]

print("msf_bank shape:", msf_bank.shape)
print("Unique PERMCO:", msf_bank["PERMCO"].nunique())
print("Unique PERMNO:", msf_bank["PERMNO"].nunique())
print("Date range:", msf_bank["DATE"].min(), "to", msf_bank["DATE"].max())

display(msf_bank.head())

Reading chunk 1: (500000, 21)
Reading chunk 2: (500000, 21)
Reading chunk 3: (500000, 21)
Reading chunk 4: (500000, 21)
Reading chunk 5: (500000, 21)
Reading chunk 6: (500000, 21)
Reading chunk 7: (500000, 21)
Reading chunk 8: (500000, 21)
Reading chunk 9: (500000, 21)
Reading chunk 10: (500000, 21)
Reading chunk 11: (153763, 21)
Final loaded shape: (5923, 11)
msf_bank shape: (5923, 13)
Unique PERMCO: 362
Unique PERMNO: 362
Date range: 2022-03-31 00:00:00 to 2023-07-31 00:00:00

      CUSIP       PERMNO      PERMCO       DATE      RET     RETX       PRC        SHROUT           VOL      HSICCD   HEXCD   abs_prc      mktcap_crsp
0  74144T10 10,138.00000 8,087.00000 2022-03-31  0.05416  0.04586 151.19000 227,810.00000 380,316.00000 6,211.00000 3.00000 151.19000 34,442,594.45618
1  74144T10 10,138.00000 8,087.00000 2022-04-29 -0.18619 -0.18619 123.04000 227,297.00000 325,938.00000 6,211.00000 3.00000 123.04000 27,966,623.08810
2  74144T10 10,138.00000 8,087.00000 2022-05-31  0.03292  0.03292 127.09000 227,297.00000 386,381.00000 6,211.00000 3.00000 127.09000 28,887,174.89761
3  74144T10 10,138.00000 8,087.00000 2022-06-30 -0.09662 -0.10607 113.61000 225,715.00000 376,969.00000 6,211.00000 3.00000 113.61000 25,643,481.28777
4  74144T10 10,138.00000 8,087.00000 2022-07-29  0.08679  0.08679 123.47000 225,692.00000 308,361.00000 6,211.00000 3.00000 123.47000 27,866,191.51550

In [36]:
# =========================================================
# Cell 7. CRSP mseall에서 보조정보 및 delisting return 추출
# =========================================================

mseall_cols = [
    "DATE", "CUSIP", "NCUSIP", "COMNAM", "TICKER",
    "PERMNO", "PERMCO",
    "SHRCD", "EXCHCD", "SICCD", "NAICS",
    "TRDSTAT", "SECSTAT",
    "DLRET", "DLRETX", "DLSTCD"
]

def filter_mseall_permco_banks(chunk):
    chunk.columns = [str(c) for c in chunk.columns]

    chunk["DATE"] = pd.to_datetime(chunk["DATE"], errors="coerce")
    chunk["PERMCO"] = pd.to_numeric(chunk["PERMCO"], errors="coerce")

    chunk = chunk[
        (chunk["DATE"] >= shock_start) &
        (chunk["DATE"] <= shock_end) &
        (chunk["PERMCO"].isin(bank_permco_set))
    ].copy()

    return chunk


mseall_bank_raw = read_sas_filtered(
    file_paths["mseall"],
    columns=mseall_cols,
    chunksize=500_000,
    filter_func=filter_mseall_permco_banks
)

mseall_bank = mseall_bank_raw.copy()

if len(mseall_bank) > 0:
    mseall_bank["CUSIP"] = mseall_bank["CUSIP"].astype(str).str[:8]
    mseall_bank["NCUSIP"] = mseall_bank["NCUSIP"].astype(str).str[:8]

    for col in ["PERMNO", "PERMCO", "SHRCD", "EXCHCD", "SICCD", "NAICS", "DLRET", "DLRETX", "DLSTCD"]:
        if col in mseall_bank.columns:
            mseall_bank[col] = pd.to_numeric(mseall_bank[col], errors="coerce")

    # 월별 delisting return
    dlret_monthly = (
        mseall_bank[
            ["PERMNO", "PERMCO", "DATE", "DLRET", "DLRETX", "DLSTCD"]
        ]
        .drop_duplicates(subset=["PERMNO", "PERMCO", "DATE"])
        .copy()
    )

    # PERMNO-DATE별 보조정보
    crsp_monthly_info = (
        mseall_bank
        .sort_values(["PERMNO", "DATE"])
        .drop_duplicates(subset=["PERMNO", "PERMCO", "DATE"], keep="last")
        [[
            "PERMNO", "PERMCO", "DATE", "CUSIP", "NCUSIP",
            "COMNAM", "TICKER", "SHRCD", "EXCHCD", "SICCD", "NAICS",
            "TRDSTAT", "SECSTAT"
        ]]
        .copy()
    )

    # PERMCO별 가장 최근 회사정보
    crsp_permco_info = (
        mseall_bank
        .sort_values(["PERMCO", "DATE"])
        .drop_duplicates(subset=["PERMCO"], keep="last")
        [[
            "PERMCO", "COMNAM", "TICKER", "SICCD", "NAICS",
            "TRDSTAT", "SECSTAT"
        ]]
        .copy()
    )

else:
    dlret_monthly = pd.DataFrame()
    crsp_monthly_info = pd.DataFrame()
    crsp_permco_info = pd.DataFrame()

print("mseall_bank shape:", mseall_bank.shape)
print("dlret_monthly shape:", dlret_monthly.shape)
print("crsp_monthly_info shape:", crsp_monthly_info.shape)
print("crsp_permco_info shape:", crsp_permco_info.shape)

display(crsp_permco_info.head())

Reading chunk 1: (500000, 50)
Reading chunk 2: (500000, 50)
Reading chunk 3: (500000, 50)
Reading chunk 4: (500000, 50)
Reading chunk 5: (500000, 50)
Reading chunk 6: (500000, 50)
Reading chunk 7: (500000, 50)
Reading chunk 8: (244882, 50)
Final loaded shape: (5739, 16)
mseall_bank shape: (5739, 16)
dlret_monthly shape: (5714, 6)
crsp_monthly_info shape: (5714, 13)
crsp_permco_info shape: (363, 7)

        PERMCO                            COMNAM TICKER       SICCD         NAICS TRDSTAT SECSTAT
2495  90.00000               AMERICAN EXPRESS CO    AXP 6,141.00000 522,291.00000       A       R
2580 137.00000  AMERICAN INTERNATIONAL GROUP INC    AIG 6,331.00000 524,126.00000       A       R
943  362.00000              ASSOCIATED BANC CORP    ASB 6,022.00000 522,110.00000       A       R
1144 475.00000                       POPULAR INC   BPOP 6,022.00000 522,110.00000       A       R
2478 579.00000                     NEWTEKONE INC   NEWT 2,330.00000 522,291.00000       A       R

In [37]:
# =========================================================
# Cell 8. Delisting-adjusted return 생성
# =========================================================

msf_adj = msf_bank.copy()

if len(dlret_monthly) > 0:
    msf_adj = msf_adj.merge(
        dlret_monthly,
        on=["PERMNO", "PERMCO", "DATE"],
        how="left"
    )
else:
    msf_adj["DLRET"] = np.nan
    msf_adj["DLRETX"] = np.nan
    msf_adj["DLSTCD"] = np.nan

# RET + DLRET 결합
msf_adj["ret_adj"] = np.nan

cond_ret_only = msf_adj["RET"].notna() & msf_adj["DLRET"].isna()
cond_both = msf_adj["RET"].notna() & msf_adj["DLRET"].notna()
cond_dlret_only = msf_adj["RET"].isna() & msf_adj["DLRET"].notna()

msf_adj.loc[cond_ret_only, "ret_adj"] = msf_adj.loc[cond_ret_only, "RET"]
msf_adj.loc[cond_both, "ret_adj"] = (
    (1 + msf_adj.loc[cond_both, "RET"]) *
    (1 + msf_adj.loc[cond_both, "DLRET"]) - 1
)
msf_adj.loc[cond_dlret_only, "ret_adj"] = msf_adj.loc[cond_dlret_only, "DLRET"]

# RETX + DLRETX도 보조로 생성
msf_adj["retx_adj"] = np.nan

cond_retx_only = msf_adj["RETX"].notna() & msf_adj["DLRETX"].isna()
cond_retx_both = msf_adj["RETX"].notna() & msf_adj["DLRETX"].notna()
cond_dlretx_only = msf_adj["RETX"].isna() & msf_adj["DLRETX"].notna()

msf_adj.loc[cond_retx_only, "retx_adj"] = msf_adj.loc[cond_retx_only, "RETX"]
msf_adj.loc[cond_retx_both, "retx_adj"] = (
    (1 + msf_adj.loc[cond_retx_both, "RETX"]) *
    (1 + msf_adj.loc[cond_retx_both, "DLRETX"]) - 1
)
msf_adj.loc[cond_dlretx_only, "retx_adj"] = msf_adj.loc[cond_dlretx_only, "DLRETX"]

print("msf_adj shape:", msf_adj.shape)
print("ret_adj missing ratio:", msf_adj["ret_adj"].isna().mean())
print("Rows with DLRET:", msf_adj["DLRET"].notna().sum())

display(msf_adj[["PERMCO", "PERMNO", "DATE", "RET", "DLRET", "ret_adj", "PRC", "SHROUT", "mktcap_crsp"]].head())

msf_adj shape: (5923, 18)
ret_adj missing ratio: 0.0016883336147222692
Rows with DLRET: 24

       PERMCO       PERMNO       DATE      RET  DLRET  ret_adj       PRC        SHROUT      mktcap_crsp
0 8,087.00000 10,138.00000 2022-03-31  0.05416    NaN  0.05416 151.19000 227,810.00000 34,442,594.45618
1 8,087.00000 10,138.00000 2022-04-29 -0.18619    NaN -0.18619 123.04000 227,297.00000 27,966,623.08810
2 8,087.00000 10,138.00000 2022-05-31  0.03292    NaN  0.03292 127.09000 227,297.00000 28,887,174.89761
3 8,087.00000 10,138.00000 2022-06-30 -0.09662    NaN -0.09662 113.61000 225,715.00000 25,643,481.28777
4 8,087.00000 10,138.00000 2022-07-29  0.08679    NaN  0.08679 123.47000 225,692.00000 27,866,191.51550

In [38]:
# =========================================================
# Cell 9. 보통주 및 주요 거래소 필터 적용
# =========================================================

crsp_returns = msf_adj.copy()

# 월별 CRSP 보조정보 붙이기
if len(crsp_monthly_info) > 0:
    info_to_merge = crsp_monthly_info.drop(columns=["CUSIP"], errors="ignore")
    crsp_returns = crsp_returns.merge(
        info_to_merge,
        on=["PERMNO", "PERMCO", "DATE"],
        how="left"
    )

print("Before filters:", crsp_returns.shape)

# 보통주만 유지: SHRCD 10, 11
if "SHRCD" in crsp_returns.columns:
    before = len(crsp_returns)
    crsp_returns = crsp_returns[
        crsp_returns["SHRCD"].isna() |
        crsp_returns["SHRCD"].isin([10, 11])
    ].copy()
    print(f"SHRCD common share filter: {before:,} -> {len(crsp_returns):,}")

# 주요 거래소만 유지: NYSE, AMEX, NASDAQ
if "EXCHCD" in crsp_returns.columns:
    before = len(crsp_returns)
    crsp_returns = crsp_returns[
        crsp_returns["EXCHCD"].isna() |
        crsp_returns["EXCHCD"].isin([1, 2, 3])
    ].copy()
    print(f"EXCHCD filter: {before:,} -> {len(crsp_returns):,}")

# 수익률 없는 행 제거
before = len(crsp_returns)
crsp_returns = crsp_returns.dropna(subset=["ret_adj"]).copy()
print(f"Drop missing ret_adj: {before:,} -> {len(crsp_returns):,}")

print("Final CRSP return data:", crsp_returns.shape)
print("Unique PERMCO:", crsp_returns["PERMCO"].nunique())
print("Unique PERMNO:", crsp_returns["PERMNO"].nunique())

display(crsp_returns.head())

Before filters: (5923, 27)
SHRCD common share filter: 5,923 -> 5,908
EXCHCD filter: 5,908 -> 5,908
Drop missing ret_adj: 5,908 -> 5,898
Final CRSP return data: (5898, 27)
Unique PERMCO: 362
Unique PERMNO: 362

,CUSIP,PERMNO,PERMCO,DATE,RET,RETX,PRC,SHROUT,VOL,HSICCD,HEXCD,abs_prc,mktcap_crsp,DLRET,DLRETX,DLSTCD,ret_adj,retx_adj,NCUSIP,COMNAM,TICKER,SHRCD,EXCHCD,SICCD,NAICS,TRDSTAT,SECSTAT
0,74144T10,"10,138.00000","8,087.00000",2022-03-31,0.05416,0.04586,151.19000,"227,810.00000","380,316.00000","6,211.00000",3.00000,151.19000,"34,442,594.45618",NaN,NaN,NaN,0.05416,0.04586,74144T10,T ROWE PRICE GROUP INC,TROW,11.00000,3.00000,"6,211.00000","523,930.00000",A,R
1,74144T10,"10,138.00000","8,087.00000",2022-04-29,-0.18619,-0.18619,123.04000,"227,297.00000","325,938.00000","6,211.00000",3.00000,123.04000,"27,966,623.08810",NaN,NaN,NaN,-0.18619,-0.18619,74144T10,T ROWE PRICE GROUP INC,TROW,11.00000,3.00000,"6,211.00000","523,930.00000",A,R
2,74144T10,"10,138.00000","8,087.00000",2022-05-31,0.03292,0.03292,127.09000,"227,297.00000","386,381.00000","6,211.00000",3.00000,127.09000,"28,887,174.89761",NaN,NaN,NaN,0.03292,0.03292,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,74144T10,"10,138.00000","8,087.00000",2022-06-30,-0.09662,-0.10607,113.61000,"225,715.00000","376,969.00000","6,211.00000",3.00000,113.61000,"25,643,481.28777",NaN,NaN,NaN,-0.09662,-0.10607,74144T10,T ROWE PRICE GROUP INC,TROW,11.00000,3.00000,"6,211.00000","523,930.00000",A,R
4,74144T10,"10,138.00000","8,087.00000",2022-07-29,0.08679,0.08679,123.47000,"225,692.00000","308,361.00000","6,211.00000",3.00000,123.47000,"27,866,191.51550",NaN,NaN,NaN,0.08679,0.08679,74144T10,T ROWE PRICE GROUP INC,TROW,11.00000,3.00000,"6,211.00000","523,930.00000",A,R

In [39]:
# =========================================================
# Cell 10. PERMCO-month 단위 수익률 생성
# =========================================================

# 한 PERMCO-DATE에 여러 PERMNO가 있으면 mktcap_crsp가 가장 큰 security 선택
permco_monthly = (
    crsp_returns
    .sort_values(
        ["PERMCO", "DATE", "mktcap_crsp"],
        ascending=[True, True, False]
    )
    .drop_duplicates(subset=["PERMCO", "DATE"], keep="first")
    .copy()
)

print("permco_monthly shape:", permco_monthly.shape)
print("Unique PERMCO:", permco_monthly["PERMCO"].nunique())
print("Unique PERMNO:", permco_monthly["PERMNO"].nunique())

# PERMCO별 몇 개 PERMNO가 있었는지 진단
permno_count_by_permco = (
    crsp_returns
    .groupby("PERMCO")["PERMNO"]
    .nunique()
    .reset_index(name="n_permno")
    .sort_values("n_permno", ascending=False)
)

print("PERMCOs with multiple PERMNOs:")
display(permno_count_by_permco.head(20))

display(permco_monthly[["PERMCO", "PERMNO", "DATE", "CUSIP", "ret_adj", "mktcap_crsp"]].head())

permco_monthly shape: (5898, 27)
Unique PERMCO: 362
Unique PERMNO: 362
PERMCOs with multiple PERMNOs:

        PERMCO  n_permno
0     90.00000         1
1    137.00000         1
2    362.00000         1
3    475.00000         1
4    579.00000         1
5    589.00000         1
6    779.00000         1
7    781.00000         1
8    840.00000         1
9  1,261.00000         1
10 1,620.00000         1
11 1,645.00000         1
12 1,658.00000         1
13 1,689.00000         1
14 1,741.00000         1
15 1,856.00000         1
16 1,940.00000         1
17 2,093.00000         1
18 2,253.00000         1
19 2,535.00000         1

       PERMCO       PERMNO       DATE     CUSIP  ret_adj       mktcap_crsp
2553 90.00000 59,176.00000 2022-03-31  02581610 -0.03876 141,613,043.00000
2554 90.00000 59,176.00000 2022-04-29  02581610 -0.06294 131,567,117.65594
2555 90.00000 59,176.00000 2022-05-31  02581610 -0.03371 127,131,594.71558
2556 90.00000 59,176.00000 2022-06-30  02581610 -0.17581 104,389,173.52295
2557 90.00000 59,176.00000 2022-07-29  02581610  0.11110 115,476,190.16327

In [40]:
# =========================================================
# Cell 11. PERMCO 기준 은행 벤치마크 수익률 생성
# =========================================================

monthly_for_bench = permco_monthly.copy()

# Equal-weight bank benchmark
ew_bench = (
    monthly_for_bench
    .groupby("DATE", as_index=False)
    .agg(ew_bank_ret=("ret_adj", "mean"))
)

# Value-weight bank benchmark
def value_weighted_return(group):
    temp = group.dropna(subset=["ret_adj", "mktcap_crsp"]).copy()
    temp = temp[temp["mktcap_crsp"] > 0]
    if len(temp) == 0:
        return np.nan
    return np.average(temp["ret_adj"], weights=temp["mktcap_crsp"])

vw_bench = (
    monthly_for_bench
    .groupby("DATE")
    .apply(value_weighted_return)
    .reset_index(name="vw_bank_ret")
)

bank_bench = ew_bench.merge(vw_bench, on="DATE", how="outer")

permco_monthly = permco_monthly.merge(
    bank_bench,
    on="DATE",
    how="left"
)

# 월별 abnormal return
permco_monthly["ew_bank_adj_ret"] = permco_monthly["ret_adj"] - permco_monthly["ew_bank_ret"]
permco_monthly["vw_bank_adj_ret"] = permco_monthly["ret_adj"] - permco_monthly["vw_bank_ret"]

print("bank_bench:")
display(bank_bench)

display(
    permco_monthly[
        ["PERMCO", "PERMNO", "DATE", "ret_adj", "ew_bank_ret", "vw_bank_ret", "ew_bank_adj_ret", "vw_bank_adj_ret"]
    ].head()
)

bank_bench:

         DATE  ew_bank_ret  vw_bank_ret
0  2022-03-31     -0.02689     -0.05137
1  2022-04-29     -0.06518     -0.10336
2  2022-05-31      0.02523      0.05753
3  2022-06-30     -0.06568     -0.12246
4  2022-07-29      0.06044      0.08457
5  2022-08-31     -0.01440     -0.01071
6  2022-09-30     -0.04872     -0.07672
7  2022-10-31      0.09019      0.13341
8  2022-11-30      0.02458      0.06155
9  2022-12-30     -0.04811     -0.06809
10 2023-01-31      0.02879      0.08805
11 2023-02-28      0.00182     -0.01143
12 2023-03-31     -0.17804     -0.14443
13 2023-04-28     -0.05752      0.01684
14 2023-05-31     -0.06313     -0.04086
15 2023-06-30      0.06317      0.06698
16 2023-07-31      0.14562      0.10403

    PERMCO       PERMNO       DATE  ret_adj  ew_bank_ret  vw_bank_ret  ew_bank_adj_ret  vw_bank_adj_ret
0 90.00000 59,176.00000 2022-03-31 -0.03876     -0.02689     -0.05137         -0.01187          0.01262
1 90.00000 59,176.00000 2022-04-29 -0.06294     -0.06518     -0.10336          0.00224          0.04042
2 90.00000 59,176.00000 2022-05-31 -0.03371      0.02523      0.05753         -0.05894         -0.09125
3 90.00000 59,176.00000 2022-06-30 -0.17581     -0.06568     -0.12246         -0.11012         -0.05335
4 90.00000 59,176.00000 2022-07-29  0.11110      0.06044      0.08457          0.05066          0.02652

In [41]:
# =========================================================
# Cell 12. 기간별 종속변수 생성
# =========================================================

periods = {
    "202203_202303": (pd.Timestamp("2022-03-01"), pd.Timestamp("2023-03-31"), 10),
    "202203_202307": (pd.Timestamp("2022-03-01"), pd.Timestamp("2023-07-31"), 13),
    "202303": (pd.Timestamp("2023-03-01"), pd.Timestamp("2023-03-31"), 1)
}

def make_y_by_period_permco(df, period_name, start, end, min_months):
    temp = df[
        (df["DATE"] >= start) &
        (df["DATE"] <= end)
    ].copy()

    y = (
        temp
        .groupby("PERMCO", as_index=False)
        .agg(
            raw_cum_ret=("ret_adj", compound_return),
            ew_adj_cum_ret=("ew_bank_adj_ret", compound_return),
            vw_adj_cum_ret=("vw_bank_adj_ret", compound_return),
            max_drawdown=("ret_adj", max_drawdown_from_returns),
            n_months=("ret_adj", lambda x: pd.to_numeric(x, errors="coerce").notna().sum()),
            first_date=("DATE", "min"),
            last_date=("DATE", "max"),
            avg_mktcap_crsp=("mktcap_crsp", "mean"),
            representative_permno=("PERMNO", "first"),
            representative_cusip=("CUSIP", "first")
        )
    )

    y = y[y["n_months"] >= min_months].copy()

    rename_dict = {
        "raw_cum_ret": f"raw_cum_ret_{period_name}",
        "ew_adj_cum_ret": f"ew_adj_cum_ret_{period_name}",
        "vw_adj_cum_ret": f"vw_adj_cum_ret_{period_name}",
        "max_drawdown": f"max_drawdown_{period_name}",
        "n_months": f"n_months_{period_name}",
        "first_date": f"first_date_{period_name}",
        "last_date": f"last_date_{period_name}",
        "avg_mktcap_crsp": f"avg_mktcap_crsp_{period_name}",
        "representative_permno": f"representative_permno_{period_name}",
        "representative_cusip": f"representative_cusip_{period_name}"
    }

    y = y.rename(columns=rename_dict)
    return y


y_data = {}

for period_name, (start, end, min_months) in periods.items():
    y_data[period_name] = make_y_by_period_permco(
        permco_monthly,
        period_name,
        start,
        end,
        min_months
    )
    print(period_name, y_data[period_name].shape)
    display(y_data[period_name].head())

y_main = y_data["202203_202303"]
y_extended = y_data["202203_202307"]
y_march = y_data["202303"]

202203_202303 (345, 11)

,PERMCO,raw_cum_ret_202203_202303,ew_adj_cum_ret_202203_202303,vw_adj_cum_ret_202203_202303,max_drawdown_202203_202303,n_months_202203_202303,first_date_202203_202303,last_date_202203_202303,avg_mktcap_crsp_202203_202303,representative_permno_202203_202303,representative_cusip_202203_202303
0,90.00000,-0.14085,0.09676,0.05586,-0.27369,13,2022-03-31,2023-03-31,"119,794,186.07620","59,176.00000",02581610
1,137.00000,-0.15311,0.09152,0.03360,-0.23372,13,2022-03-31,2023-03-31,"43,703,519.26920","66,800.00000",02687478
2,362.00000,-0.23497,0.00777,-0.04623,-0.26248,13,2022-03-31,2023-03-31,"3,205,858.47069","15,318.00000",04548710
3,475.00000,-0.34995,-0.17326,-0.22550,-0.27443,13,2022-03-31,2023-03-31,"5,442,296.99138","16,505.00000",73317470
5,589.00000,-0.37375,-0.17540,-0.22974,-0.35689,13,2022-03-31,2023-03-31,"3,039,348.05951","16,548.00000",06254010

202203_202307 (342, 11)

,PERMCO,raw_cum_ret_202203_202307,ew_adj_cum_ret_202203_202307,vw_adj_cum_ret_202203_202307,max_drawdown_202203_202307,n_months_202203_202307,first_date_202203_202307,last_date_202203_202307,avg_mktcap_crsp_202203_202307,representative_permno_202203_202307,representative_cusip_202203_202307
0,90.00000,-0.11397,0.02122,-0.06518,-0.27369,17,2022-03-31,2023-07-31,"120,525,469.98835","59,176.00000",02581610
1,137.00000,0.02006,0.19627,0.07845,-0.23372,17,2022-03-31,2023-07-31,"42,985,751.91817","66,800.00000",02687478
2,362.00000,-0.18226,0.01048,-0.10134,-0.38389,17,2022-03-31,2023-07-31,"3,053,538.60805","15,318.00000",04548710
3,475.00000,-0.17062,-0.02035,-0.13299,-0.27443,17,2022-03-31,2023-07-31,"5,222,287.84131","16,505.00000",73317470
5,589.00000,-0.30074,-0.11445,-0.23228,-0.50791,17,2022-03-31,2023-07-31,"2,758,139.60003","16,548.00000",06254010

202303 (343, 11)

     PERMCO  raw_cum_ret_202303  ew_adj_cum_ret_202303  vw_adj_cum_ret_202303  max_drawdown_202303  n_months_202303 first_date_202303 last_date_202303  avg_mktcap_crsp_202303  representative_permno_202303 representative_cusip_202303
0  90.00000            -0.05196                0.12608                0.09247              0.00000                1        2023-03-31       2023-03-31       122,754,633.07890                  59,176.00000                    02581610
1 137.00000            -0.17068                0.00736               -0.02625              0.00000                1        2023-03-31       2023-03-31        37,127,759.36998                  66,800.00000                    02687478
2 362.00000            -0.22333               -0.04529               -0.07890              0.00000                1        2023-03-31       2023-03-31         2,706,745.09109                  15,318.00000                    04548710
3 475.00000            -0.18824               -0.01020               -0.04381              0.00000                1        2023-03-31       2023-03-31         4,131,568.04902                  16,505.00000                    73317470
4 589.00000            -0.30430               -0.12626               -0.15988              0.00000                1        2023-03-31       2023-03-31         2,072,002.87285                  16,548.00000                    06254010

In [42]:
# =========================================================
# Cell 13. Compustat funda에서 2020-2021 회계자료 추출
# =========================================================

funda_cols = [
    "gvkey", "datadate", "fyear", "fyr",
    "indfmt", "consol", "popsrc", "datafmt",
    "tic", "cusip", "conm",
    "sich", "naicsh", "costat", "fic",
    "at", "ceq", "seq", "lt", "ni", "sale",
    "che", "dltt", "dlc", "prcc_f", "csho",
    "act", "lct"
]

def filter_funda_2020_2021_us_standard(chunk):
    chunk["fyear"] = pd.to_numeric(chunk["fyear"], errors="coerce")

    # 2020: asset growth 계산용
    # 2021: pre-shock accounting variables
    chunk = chunk[chunk["fyear"].isin([2020, 2021])].copy()

    # 미국 기업
    if "fic" in chunk.columns:
        chunk = chunk[chunk["fic"].eq("USA")].copy()

    # Compustat standard filters
    if "indfmt" in chunk.columns:
        chunk = chunk[chunk["indfmt"].eq("INDL")].copy()
    if "consol" in chunk.columns:
        chunk = chunk[chunk["consol"].eq("C")].copy()
    if "datafmt" in chunk.columns:
        chunk = chunk[chunk["datafmt"].eq("STD")].copy()

    return chunk


funda_raw = read_sas_filtered(
    file_paths["funda"],
    columns=funda_cols,
    chunksize=300_000,
    filter_func=filter_funda_2020_2021_us_standard
)

funda = funda_raw.copy()

# 숫자형 변환
num_cols = [
    "fyear", "at", "ceq", "seq", "lt", "ni", "sale",
    "che", "dltt", "dlc", "prcc_f", "csho",
    "act", "lct", "sich"
]

for col in num_cols:
    if col in funda.columns:
        funda[col] = pd.to_numeric(funda[col], errors="coerce")

funda["sich_num"] = pd.to_numeric(funda["sich"], errors="coerce")
funda["cusip8"] = funda["cusip"].astype(str).str[:8]

print("funda shape:", funda.shape)
print("Unique gvkey:", funda["gvkey"].nunique())
display(funda.head())

Reading chunk 1: (300000, 949)
Reading chunk 2: (300000, 949)
Reading chunk 3: (300000, 949)
Reading chunk 4: (38671, 949)
Final loaded shape: (16835, 28)
funda shape: (16835, 30)
Unique gvkey: 8969

,gvkey,datadate,fyear,fyr,indfmt,consol,popsrc,datafmt,tic,cusip,conm,sich,naicsh,costat,fic,at,ceq,seq,lt,ni,sale,che,dltt,dlc,prcc_f,csho,act,lct,sich_num,cusip8
0,001004,2021-05-31,"2,020.00000",5.00000,INDL,C,D,STD,AIR,000361105,AAR CORP,"5,080.00000","423,860.00000",A,USA,"1,539.70000",974.40000,974.40000,565.30000,35.80000,"1,651.40000",60.20000,193.60000,11.50000,41.75000,35.37500,937.00000,336.80000,"5,080.00000",00036110
1,001004,2022-05-31,"2,021.00000",5.00000,INDL,C,D,STD,AIR,000361105,AAR CORP,"5,080.00000","423,860.00000",A,USA,"1,573.90000","1,034.50000","1,034.50000",539.40000,78.70000,"1,817.10000",58.90000,156.30000,11.10000,48.22000,35.39100,"1,007.20000",348.20000,"5,080.00000",00036110
2,001019,2020-12-31,"2,020.00000",12.00000,INDL,C,D,STD,AFAP,001038108,AFA PROTECTIVE SYSTEMS INC,"7,380.00000","561,621.00000",I,USA,40.57000,13.47900,13.47900,27.09100,2.60300,82.67900,6.05300,6.66800,2.00000,174.00000,0.16200,31.09800,15.57300,"7,380.00000",00103810
3,001045,2020-12-31,"2,020.00000",12.00000,INDL,C,D,STD,AAL,02376R102,AMERICAN AIRLINES GROUP INC,"4,512.00000","481,111.00000",A,USA,"62,008.00000","-6,867.00000","-6,867.00000","68,875.00000","-8,885.00000","17,337.00000","7,473.00000","36,573.00000","4,448.00000",15.77000,621.48000,"11,095.00000","16,569.00000","4,512.00000",02376R10
4,001045,2021-12-31,"2,021.00000",12.00000,INDL,C,D,STD,AAL,02376R102,AMERICAN AIRLINES GROUP INC,"4,512.00000","481,111.00000",A,USA,"66,467.00000","-7,340.00000","-7,340.00000","73,807.00000","-1,993.00000","29,882.00000","13,421.00000","42,181.00000","3,996.00000",17.96000,647.72800,"17,336.00000","19,006.00000","4,512.00000",02376R10

In [43]:
# =========================================================
# Cell 14. 2021년 pre-shock 회계변수 생성
# =========================================================

# 2020 총자산: asset growth 계산용
at_2020 = (
    funda[funda["fyear"] == 2020]
    [["gvkey", "at"]]
    .dropna(subset=["gvkey", "at"])
    .sort_values(["gvkey", "at"], ascending=[True, False])
    .drop_duplicates(subset=["gvkey"])
    .rename(columns={"at": "at_2020"})
)

# 2021 회계정보
x_2021 = funda[funda["fyear"] == 2021].copy()

# market cap 계산
x_2021["market_cap_compustat"] = x_2021["prcc_f"] * x_2021["csho"]

# 중복 제거
x_2021 = (
    x_2021
    .sort_values(
        ["gvkey", "cusip8", "market_cap_compustat"],
        ascending=[True, True, False]
    )
    .drop_duplicates(subset=["gvkey", "cusip8"])
    .copy()
)

# 2020 자산 붙이기
x_2021 = x_2021.merge(at_2020, on="gvkey", how="left")

# 주요 변수 생성
x_2021["size"] = np.log(x_2021["at"])
x_2021["equity_ratio"] = safe_divide(x_2021["ceq"], x_2021["at"])
x_2021["roa"] = safe_divide(x_2021["ni"], x_2021["at"])
x_2021["cash_ratio"] = safe_divide(x_2021["che"], x_2021["at"])
x_2021["debt_ratio"] = safe_divide(x_2021["dltt"].fillna(0) + x_2021["dlc"].fillna(0), x_2021["at"])
x_2021["market_to_book"] = safe_divide(x_2021["market_cap_compustat"], x_2021["ceq"])
x_2021["asset_growth"] = safe_divide(x_2021["at"] - x_2021["at_2020"], x_2021["at_2020"])

# 참고용 변수
x_2021["leverage"] = safe_divide(x_2021["lt"], x_2021["at"])
x_2021["current_ratio"] = safe_divide(x_2021["act"], x_2021["lct"])

x_vars_main = [
    "size",
    "equity_ratio",
    "roa",
    "cash_ratio",
    "debt_ratio",
    "asset_growth",
    "market_to_book"
]

x_vars_extended = x_vars_main + [
    "leverage",
    "current_ratio"
]

x_data_all = x_2021[
    [
        "gvkey", "cusip", "cusip8", "tic", "conm",
        "sich_num", "naicsh", "at", "market_cap_compustat"
    ] + x_vars_extended
].copy()

x_data_all = x_data_all.replace([np.inf, -np.inf], np.nan)

print("x_data_all shape:", x_data_all.shape)
print("Unique gvkey:", x_data_all["gvkey"].nunique())
display(x_data_all.head())
display(x_data_all[x_vars_extended].describe().T)

x_data_all shape: (8555, 18)
Unique gvkey: 8555

    gvkey      cusip    cusip8   tic                         conm    sich_num        naicsh           at  market_cap_compustat     size  equity_ratio      roa  cash_ratio  debt_ratio  asset_growth  market_to_book  leverage  current_ratio
0  001004  000361105  00036110   AIR                     AAR CORP 5,080.00000 423,860.00000  1,573.90000           1,706.55402  7.36131       0.65728  0.05000     0.03742     0.10636       0.02221         1.64964   0.34272        2.89259
1  001045  02376R102  02376R10   AAL  AMERICAN AIRLINES GROUP INC 4,512.00000 481,111.00000 66,467.00000          11,633.19488 11.10446      -0.11043 -0.02998     0.20192     0.69474       0.07191        -1.58490   1.11043        0.91213
2  001050  125141101  12514110  CECO      CECO ENVIRONMENTAL CORP 3,564.00000 333,413.00000    416.19700             218.22444  6.03116       0.49148  0.00343     0.07687     0.19639      -0.00743         1.06683   0.50515        1.61984
3  001075  723484101  72348410   PNW   PINNACLE WEST CAPITAL CORP 4,911.00000   2,211.00000 22,003.22200           7,971.51693  9.99894       0.26842  0.02812     0.00045     0.37197       0.09904         1.34969   0.72634        0.88288
4  001076  74319R101  74319R10   PRG            PROG HOLDINGS INC 6,141.00000 522,220.00000  1,621.76100           2,546.05351  7.39127       0.41893  0.15018     0.10492     0.37926       0.23103         3.74746   0.58107            NaN

                     count     mean         std           min      25%     50%     75%           max
size           5,369.00000  6.39435     2.87502      -6.90776  4.78733 6.73497 8.27825      15.25752
equity_ratio   5,358.00000 -1.93289    37.37351  -1,427.66176  0.13423 0.38896 0.65289       1.53920
roa            5,358.00000 -4.47345   215.52545 -15,612.60000 -0.16602 0.00936 0.05162      20.20000
cash_ratio     5,369.00000  0.28133     0.30306       0.00000  0.04634 0.14083 0.45549       1.00000
debt_ratio     5,369.00000  1.16501    15.34625       0.00000  0.03874 0.21299 0.42615     629.00000
asset_growth   5,057.00000 55.95906 2,335.85680      -1.00000 -0.00299 0.09157 0.33467 150,021.00000
market_to_book 5,038.00000 31.01920 1,404.14163 -11,109.50000  1.05571 2.00730 4.40503  82,826.02632
leverage       5,359.00000  2.82930    36.71149       0.00000  0.32624 0.58117 0.83488   1,399.25000
current_ratio  4,268.00000  6.78864   124.12340       0.00000  1.13135 1.99455 4.35145   8,074.41667

In [44]:
# =========================================================
# Cell 15. PERMCO 은행 표본과 Compustat 회계변수 연결
# =========================================================

# CRSP에서 관측된 PERMCO-CUSIP mapping 생성
permco_cusip_map = (
    permco_monthly
    .dropna(subset=["PERMCO", "CUSIP"])
    .groupby(["PERMCO", "CUSIP"], as_index=False)
    .agg(
        n_months_map=("DATE", "nunique"),
        avg_mktcap_map=("mktcap_crsp", "mean"),
        representative_permno_map=("PERMNO", "first")
    )
)

print("permco_cusip_map shape:", permco_cusip_map.shape)
display(permco_cusip_map.head())

# CUSIP으로 Compustat 연결
permco_x_candidates = permco_cusip_map.merge(
    x_data_all,
    left_on="CUSIP",
    right_on="cusip8",
    how="inner"
)

print("PERMCO-Compustat candidate matches:", permco_x_candidates.shape)
print("Matched unique PERMCO:", permco_x_candidates["PERMCO"].nunique())
print("Matched unique gvkey:", permco_x_candidates["gvkey"].nunique())

# PERMCO별 대표 Compustat record 선택
# 우선순위: mapping 관측월 수 많음, CRSP 평균시총 큼, Compustat 시총 큼
permco_x = (
    permco_x_candidates
    .sort_values(
        ["PERMCO", "n_months_map", "avg_mktcap_map", "market_cap_compustat"],
        ascending=[True, False, False, False]
    )
    .drop_duplicates(subset=["PERMCO"], keep="first")
    .copy()
)

print("Final PERMCO accounting data:", permco_x.shape)
print("Unique PERMCO:", permco_x["PERMCO"].nunique())
print("Unique gvkey:", permco_x["gvkey"].nunique())

# 매칭률 진단
matched_permcos = set(permco_x["PERMCO"].dropna().astype(int))
return_permcos = set(y_main["PERMCO"].dropna().astype(int))
unmatched_permcos = sorted(list(return_permcos - matched_permcos))

print("PERMCOs with return data:", len(return_permcos))
print("PERMCOs matched to Compustat:", len(matched_permcos))
print("Return PERMCOs not matched to Compustat:", len(unmatched_permcos))

display(permco_x[["PERMCO", "gvkey", "conm", "tic", "sich_num", "CUSIP", "cusip8"] + x_vars_main].head(50))

permco_cusip_map shape: (362, 5)

     PERMCO     CUSIP  n_months_map    avg_mktcap_map  representative_permno_map
0  90.00000  02581610            17 120,525,469.98835               59,176.00000
1 137.00000  02687478            17  42,985,751.91817               66,800.00000
2 362.00000  04548710            17   3,053,538.60805               15,318.00000
3 475.00000  73317470            17   5,222,287.84131               16,505.00000
4 579.00000  65252620             2     490,877.63122               58,836.00000

PERMCO-Compustat candidate matches: (354, 23)
Matched unique PERMCO: 354
Matched unique gvkey: 354
Final PERMCO accounting data: (354, 23)
Unique PERMCO: 354
Unique gvkey: 354
PERMCOs with return data: 345
PERMCOs matched to Compustat: 354
Return PERMCOs not matched to Compustat: 7

        PERMCO   gvkey                          conm   tic    sich_num     CUSIP    cusip8     size  equity_ratio     roa  cash_ratio  debt_ratio  asset_growth  market_to_book
0     90.00000  001447           AMERICAN EXPRESS CO   AXP 6,141.00000  02581610  02581610 12.14711       0.11762 0.04275     0.12466     0.22296      -0.01473         5.61391
1    137.00000  001487  AMERICAN INTERNATIONAL GROUP   AIG 6,331.00000  02687478  02687478 13.29818       0.10983 0.01575     0.03895     0.06484       0.01642         0.71101
2    362.00000  011842          ASSOCIATED BANC-CORP   ASB 6,020.00000  04548710  04548710 10.46608       0.10915 0.01000     0.02921     0.06427       0.05040         0.88047
3    475.00000  002002                   POPULAR INC  BPOP 6,020.00000  73317470  73317470 11.22655       0.07919 0.01245     0.23922     0.01770       0.13912         1.10151
4    579.00000  008060                 NEWTEKONE INC  NEWT 6,797.00000  65252620  65252620  6.96277       0.38227 0.07964     0.17686     0.45535       0.25635         1.65272
5    589.00000  002005           BANK OF HAWAII CORP   BOH 6,020.00000  06254010  06254010 10.03386       0.06283 0.01112     0.02460     0.02476       0.10587         2.35510
6    779.00000  003238       COMMERCE BANCSHARES INC  CBSH 6,020.00000  20052510  20052510 10.51023       0.09369 0.01447     0.11664     0.08348       0.11439         2.43347
7    781.00000  013041        SYNOVUS FINANCIAL CORP   SNV 6,020.00000  87161C50  87161C50 10.95636       0.08304 0.01327     0.05251     0.02562       0.05374         1.45843
8    840.00000  003643      CULLEN/FROST BANKERS INC   CFR 6,020.00000  22989910  22989910 10.83720       0.08440 0.00871     0.32593     0.06491       0.20021         1.87856
9  1,261.00000  003231                  COMERICA INC   CMA 6,020.00000  20034010  20034010 11.45758       0.07930 0.01234     0.23970     0.03331       0.07361         1.51537
10 1,620.00000  004674        REGIONS FINANCIAL CORP    RF 6,020.00000  7591EP10  7591EP10 12.00113       0.10229 0.01547     0.18050     0.01802       0.10550         1.23199
11 1,645.00000  004723                    US BANCORP   USB 6,020.00000  90297330  90297330 13.25914       0.08468 0.01389     0.05105     0.07865       0.03499         1.71645
12 1,658.00000  004685                TRUSTMARK CORP  TRMK 6,020.00000  89840210  89840210  9.77541       0.09896 0.00838     0.12883     0.03131       0.06306         1.14921
13 1,689.00000  004699                 M&T BANK CORP   MTB 6,020.00000  55261F10  55261F10 11.95187       0.10414 0.01198     0.27858     0.02555       0.08770         1.22352
14 1,741.00000  004640           FIFTH THIRD BANCORP  FITB 6,020.00000  31677310  31677310 12.26016       0.09518 0.01312     0.17794     0.06443       0.03144         1.47979
15 1,856.00000  004737            FIRST HORIZON CORP   FHN 6,020.00000  32051710  32051710 11.39742       0.08619 0.01121     0.18739     0.04602       0.05799         1.13469
16 1,940.00000  016668          ARROW FINANCIAL CORP  AROW 6,020.00000  04274410  04274410  8.30101       0.09215 0.01238     0.11363     0.01919       0.09199         1.52248
17 2,093.00000  005786         HUNTINGTON BANCSHARES  HBAN 6,020.00000  44615010  44615010 12.06718       0.09841 0.00744     0.03398     0.04529       0.41472         1.29422
18 2,253.00000  014253    WESTAMERICA BANCORPORATION  WABC 6,020.00000  95709010  95709010  8.91745       0.11086 0.01159     0.15173     0.02201       0.10568         1.87519
19 2,535.00000  009783                       KEYCORP   KEY 6,020.00000  49326710  49326710 12.13536       0.08330 0.01409     0.06398     0.07233       0.09399         1.38403
20 3,151.00000  007647          BANK OF AMERICA CORP   BAC 6,020.00000  06050510  06050510 14.96908       0.07741 0.01009     0.19122     0.15998       0.12408         1.46473
21 3,275.00000  007982           NORTHERN TRUST CORP  NTRS 6,020.00000  66585910  66585910 12.12209       0.06054 0.00840     0.38216     0.04584       0.08168         2.23236
22 3,685.00000  008245  PNC FINANCIAL SVCS GROUP INC   PNC 6,020.00000  69347510  69347510 13.23066       0.09097 0.01018     0.14762     0.05923       0.19395         1.66157
23 4,040.00000  009317            SEI INVESTMENTS CO  SEIC 6,282.00000  78411710  78411710  7.76417       0.79023 0.23213     0.35323     0.03354       0.08649         4.53421
24 4,163.00000  011856         TRUIST FINANCIAL CORP   TFC 6,020.00000  89832Q10  89832Q10 13.20162       0.11566 0.01190     0.04389     0.07909       0.06287         1.24195
25 4,260.00000  010035             STATE STREET CORP   STT 6,020.00000  85747710  85747710 12.65913       0.08069 0.00856     0.35916     0.05095      -0.00026         1.34070
26 4,673.00000  010916            UMB FINANCIAL CORP  UMBF 6,020.00000  90278810  90278810 10.66180       0.07367 0.00827     0.24529     0.08373       0.28876         1.63381
27 4,818.00000  011861       VALLEY NATIONAL BANCORP   VLY 6,020.00000  91979410  91979410 10.67928       0.11219 0.01091     0.04718     0.05568       0.06785         1.18882
28 5,057.00000  011687       ZIONS BANCORPORATION NA  ZION 6,020.00000  98970110  98970110 11.44250       0.07535 0.01211     0.13960     0.02293       0.14385         1.36361
29 5,440.00000  014172         FULTON FINANCIAL CORP  FULT 6,020.00000  36027110  36027110 10.15799       0.09768 0.01068     0.06352     0.04384      -0.00426         1.08276
30 5,679.00000  017145                      WAFD INC  WAFD 6,020.00000  93882410  93882410  9.88586       0.09293 0.00934     0.10640     0.08903       0.04557         1.22401
31 5,856.00000  020019            CVB FINANCIAL CORP  CVBF 6,020.00000  12660010  12660010  9.67305       0.13105 0.01338     0.11071     0.04507       0.10156         1.39400
32 5,926.00000  017245          TRUSTCO BANK CORP/NY  TRST 6,035.00000  89834920  89834920  8.73175       0.09701 0.00993     0.19680     0.04800       0.04994         1.06503
33 6,137.00000  008898   RAYMOND JAMES FINANCIAL INC   RJF 6,211.00000  75473010  75473010 11.03313       0.13322 0.02267     0.30421     0.06020       0.30346         2.30268
34 6,185.00000  011770         STIFEL FINANCIAL CORP    SF 6,211.00000  86063010  86063010 10.43558       0.12775 0.02423     0.08125     0.09146       0.27986         1.69170
35 6,281.00000  015199               1ST SOURCE CORP  SRCE 6,020.00000  33690110  33690110  8.99916       0.11317 0.01464     0.06487     0.04340       0.10659         1.33926
36 6,407.00000  004885        FRANKLIN RESOURCES INC   BEN 6,282.00000  35461310  35461310 10.09280       0.46438 0.07577     0.19228     0.31400       0.19522         1.32881
37 6,736.00000  017195     FIRST FINL BANCORP INC/OH  FFBC 6,020.00000  32020910  32020910  9.70071       0.13834 0.01256     0.02663     0.04737       0.02229         1.01612
38 6,827.00000  017184      SEACOAST BANKING CORP/FL  SBCF 6,020.00000  81170780  81170780  9.17797       0.13539 0.01285     0.07620     0.02392       0.16051         1.57961
39 6,944.00000  016832           GLACIER BANCORP INC  GBCI 6,020.00000  37637Q10  37637Q10 10.16357       0.12250 0.01098     0.01687     0.04801       0.40188         1.97506
40 7,067.00000  017095          OLD NATIONAL BANCORP   ONB 6,020.00000  68003310  68003310 10.10453       0.12317 0.01135     0.03362     0.10843       0.06502         0.99766
41 7,407.00000  017269    AMERISERV FINANCIAL INC/PA  ASRV 6,020.00000  03074A10  03074A10  7.19711       0.08727 0.00530     0.03077     0.05454       0.04364         0.56574
42 7,460.00000  019355  SIMMONS FIRST NATL CP  -CL A  SFNC 6,020.00000  82873020  82873020 10.11556       0.13140 0.01097     0.06684     0.07914       0.10577         1.02625
43 7,720.00000  016890      INDEPENDENT BANK CORP/MI  IBCP 6,020.00000  45383860  45383860  8.45633       0.08470 0.01337     0.02327     0.02456       0.11911         1.26819
44 7,784.00000  014219                  CADENCE BANK  CADE 6,020.00000  12740C10  12740C10 10.77205       0.10659 0.00409     0.02716     0.03702       0.97954         1.10423
45 7,788.00000  016989        PEOPLES BANCORP NC INC  PEBK 6,020.00000  71057710  71057710  7.39277       0.08766 0.00932     0.17085     0.03524       0.14796         1.09725
46 7,871.00000  016790  COMMUNITY FINANCIAL SYST INC   CBU 6,020.00000  20360710  20360710  9.65199       0.13508 0.01220     0.12056     0.02332       0.11640         1.91014
47 8,087.00000  012138         PRICE (T. ROWE) GROUP  TROW 6,282.00000  74144T10  74144T10  9.43420       0.72130 0.24645     0.12984     0.02894       0.17356         4.99462
48 8,158.00000  017987    ELMIRA SVGS BANK ELMIRA/NY  ESBK         NaN  28966010  28966010  6.44926       0.08577 0.00825     0.16108     0.03480      -0.01917         1.49445
49 8,179.00000  016889      INDEPENDENT BANK CORP/MA  INDB 6,020.00000  45383610  45383610  9.92444       0.14779 0.00592     0.10971     0.01059       0.54672         1.27895

In [45]:
# =========================================================
# Cell 16. 최종 분석 데이터 생성
# =========================================================

analysis_df = y_main.merge(
    permco_x,
    on="PERMCO",
    how="left"
)

analysis_df = analysis_df.merge(
    y_extended.drop(columns=[
        "representative_permno_202203_202307",
        "representative_cusip_202203_202307"
    ], errors="ignore"),
    on="PERMCO",
    how="left"
)

analysis_df = analysis_df.merge(
    y_march.drop(columns=[
        "representative_permno_202303",
        "representative_cusip_202303"
    ], errors="ignore"),
    on="PERMCO",
    how="left"
)

# CRSP PERMCO 회사정보 붙이기
if len(crsp_permco_info) > 0:
    analysis_df = analysis_df.merge(
        crsp_permco_info,
        on="PERMCO",
        how="left",
        suffixes=("", "_crsp")
    )

print("analysis_df shape:", analysis_df.shape)
print("Unique PERMCO:", analysis_df["PERMCO"].nunique())
print("Unique gvkey matched:", analysis_df["gvkey"].nunique())

print("\nCompustat match missing:")
print(analysis_df["gvkey"].isna().sum())

print("\nSIC distribution from Compustat:")
display(analysis_df["sich_num"].value_counts(dropna=False).sort_index())

display(
    analysis_df[
        [
            "PERMCO", "gvkey", "conm", "tic", "COMNAM", "TICKER",
            "sich_num", "representative_permno_202203_202303",
            "raw_cum_ret_202203_202303",
            "vw_adj_cum_ret_202203_202303"
        ] + x_vars_main
    ].head(50)
)

analysis_df shape: (345, 55)
Unique PERMCO: 345
Unique gvkey matched: 338

Compustat match missing:
7

SIC distribution from Compustat:

sich_num
6,020.00000    280
6,035.00000     21
6,036.00000     14
6,141.00000      6
6,162.00000      1
6,172.00000      1
6,199.00000      2
6,211.00000      4
6,282.00000      5
6,311.00000      1
6,331.00000      1
6,361.00000      1
7,389.00000      1
NaN              7
Name: count, dtype: int64

,PERMCO,gvkey,conm,tic,COMNAM,TICKER,sich_num,representative_permno_202203_202303,raw_cum_ret_202203_202303,vw_adj_cum_ret_202203_202303,size,equity_ratio,roa,cash_ratio,debt_ratio,asset_growth,market_to_book
0,90.00000,001447,AMERICAN EXPRESS CO,AXP,AMERICAN EXPRESS CO,AXP,"6,141.00000","59,176.00000",-0.14085,0.05586,12.14711,0.11762,0.04275,0.12466,0.22296,-0.01473,5.61391
1,137.00000,001487,AMERICAN INTERNATIONAL GROUP,AIG,AMERICAN INTERNATIONAL GROUP INC,AIG,"6,331.00000","66,800.00000",-0.15311,0.03360,13.29818,0.10983,0.01575,0.03895,0.06484,0.01642,0.71101
2,362.00000,011842,ASSOCIATED BANC-CORP,ASB,ASSOCIATED BANC CORP,ASB,"6,020.00000","15,318.00000",-0.23497,-0.04623,10.46608,0.10915,0.01000,0.02921,0.06427,0.05040,0.88047
3,475.00000,002002,POPULAR INC,BPOP,POPULAR INC,BPOP,"6,020.00000","16,505.00000",-0.34995,-0.22550,11.22655,0.07919,0.01245,0.23922,0.01770,0.13912,1.10151
4,589.00000,002005,BANK OF HAWAII CORP,BOH,BANK OF HAWAII CORP,BOH,"6,020.00000","16,548.00000",-0.37375,-0.22974,10.03386,0.06283,0.01112,0.02460,0.02476,0.10587,2.35510
5,779.00000,003238,COMMERCE BANCSHARES INC,CBSH,COMMERCE BANCSHARES INC,CBSH,"6,020.00000","25,129.00000",-0.12918,0.02481,10.51023,0.09369,0.01447,0.11664,0.08348,0.11439,2.43347
6,781.00000,013041,SYNOVUS FINANCIAL CORP,SNV,SYNOVUS FINANCIAL CORP,SNV,"6,020.00000","20,053.00000",-0.38651,-0.21985,10.95636,0.08304,0.01327,0.05251,0.02562,0.05374,1.45843
7,840.00000,003643,CULLEN/FROST BANKERS INC,CFR,CULLEN FROST BANKERS INC,CFR,"6,020.00000","27,888.00000",-0.23236,-0.07646,10.83720,0.08440,0.00871,0.32593,0.06491,0.20021,1.87856
8,"1,261.00000",003231,COMERICA INC,CMA,COMERICA INC,CMA,"6,020.00000","25,081.00000",-0.52075,-0.39178,11.45758,0.07930,0.01234,0.23970,0.03331,0.07361,1.51537
9,"1,620.00000",004674,REGIONS FINANCIAL CORP,RF,REGIONS FINANCIAL CORP NEW,RF,"6,020.00000","35,044.00000",-0.19622,0.00294,12.00113,0.10229,0.01547,0.18050,0.01802,0.10550,1.23199
10,"1,645.00000",004723,US BANCORP,USB,U S BANCORP DEL,USB,"6,020.00000","66,157.00000",-0.32664,-0.15973,13.25914,0.08468,0.01389,0.05105,0.07865,0.03499,1.71645
11,"1,658.00000",004685,TRUSTMARK CORP,TRMK,TRUSTMARK CORP,TRMK,"6,020.00000","35,263.00000",-0.19238,-0.04183,9.77541,0.09896,0.00838,0.12883,0.03131,0.06306,1.14921
12,"1,689.00000",004699,M&T BANK CORP,MTB,M & T BANK CORP,MTB,"6,020.00000","35,554.00000",-0.32314,-0.17627,11.95187,0.10414,0.01198,0.27858,0.02555,0.08770,1.22352
13,"1,741.00000",004640,FIFTH THIRD BANCORP,FITB,FIFTH THIRD BANCORP,FITB,"6,020.00000","34,746.00000",-0.41551,-0.26122,12.26016,0.09518,0.01312,0.17794,0.06443,0.03144,1.47979
14,"1,856.00000",004737,FIRST HORIZON CORP,FHN,FIRST HORIZON CORP,FHN,"6,020.00000","36,397.00000",-0.21638,-0.05833,11.39742,0.08619,0.01121,0.18739,0.04602,0.05799,1.13469
15,"1,940.00000",016668,ARROW FINANCIAL CORP,AROW,ARROW FINANCIAL CORP,AROW,"6,020.00000","15,070.00000",-0.22652,-0.06122,8.30101,0.09215,0.01238,0.11363,0.01919,0.09199,1.52248
16,"2,093.00000",005786,HUNTINGTON BANCSHARES,HBAN,HUNTINGTON BANCSHARES INC,HBAN,"6,020.00000","42,906.00000",-0.23394,-0.03494,12.06718,0.09841,0.00744,0.03398,0.04529,0.41472,1.29422
17,"2,253.00000",014253,WESTAMERICA BANCORPORATION,WABC,WESTAMERICA BANCORPORATION,WABC,"6,020.00000","82,107.00000",-0.23138,-0.06991,8.91745,0.11086,0.01159,0.15173,0.02201,0.10568,1.87519
18,"2,535.00000",009783,KEYCORP,KEY,KEYCORP NEW,KEY,"6,020.00000","64,995.00000",-0.47883,-0.32528,12.13536,0.08330,0.01409,0.06398,0.07233,0.09399,1.38403
19,"3,151.00000",007647,BANK OF AMERICA CORP,BAC,BANK OF AMERICA CORP,BAC,"6,020.00000","59,408.00000",-0.33100,-0.15272,14.96908,0.07741,0.01009,0.19122,0.15998,0.12408,1.46473
20,"3,275.00000",007982,NORTHERN TRUST CORP,NTRS,NORTHERN TRUST CORP,NTRS,"6,020.00000","58,246.00000",-0.19559,-0.03593,12.12209,0.06054,0.00840,0.38216,0.04584,0.08168,2.23236
21,"3,685.00000",008245,PNC FINANCIAL SVCS GROUP INC,PNC,P N C FINANCIAL SERVICES GRP INC,PNC,"6,020.00000","60,442.00000",-0.33857,-0.18537,13.23066,0.09097,0.01018,0.14762,0.05923,0.19395,1.66157
22,"4,040.00000",009317,SEI INVESTMENTS CO,SEIC,S E I INVESTMENTS CO,SEIC,"6,282.00000","68,196.00000",-0.00301,0.19532,7.76417,0.79023,0.23213,0.35323,0.03354,0.08649,4.53421
23,"4,163.00000",011856,TRUIST FINANCIAL CORP,TFC,TRUIST FINANCIAL CORP,TFC,"6,020.00000","71,563.00000",-0.42803,-0.28239,13.20162,0.11566,0.01190,0.04389,0.07909,0.06287,1.24195
24,"4,260.00000",010035,STATE STREET CORP,STT,STATE STREET CORP,STT,"6,020.00000","72,726.00000",-0.07455,0.19025,12.65913,0.08069,0.00856,0.35916,0.05095,-0.00026,1.34070
25,"4,673.00000",010916,UMB FINANCIAL CORP,UMBF,U M B FINANCIAL CORP,UMBF,"6,020.00000","78,829.00000",-0.41982,-0.27890,10.66180,0.07367,0.00827,0.24529,0.08373,0.28876,1.63381
26,"4,818.00000",011861,VALLEY NATIONAL BANCORP,VLY,VALLEY NATIONAL BANCORP,VLY,"6,020.00000","80,072.00000",-0.30427,-0.12833,10.67928,0.11219,0.01091,0.04718,0.05568,0.06785,1.18882
27,"5,057.00000",011687,ZIONS BANCORPORATION NA,ZION,ZIONS BANCORPORATION N A,ZION,"6,020.00000","84,129.00000",-0.56493,-0.43729,11.44250,0.07535,0.01211,0.13960,0.02293,0.14385,1.36361
28,"5,440.00000",014172,FULTON FINANCIAL CORP,FULT,FULTON FINANCIAL CORP PA,FULT,"6,020.00000","88,197.00000",-0.19242,-0.00548,10.15799,0.09768,0.01068,0.06352,0.04384,-0.00426,1.08276
29,"5,679.00000",017145,WAFD INC,WAFD,WASHINGTON FEDERAL INC,WAFD,"6,020.00000","81,577.00000",-0.12879,0.07731,9.88586,0.09293,0.00934,0.10640,0.08903,0.04557,1.22401
30,"5,856.00000",020019,CVB FINANCIAL CORP,CVBF,C V B FINANCIAL CORP,CVBF,"6,020.00000","20,395.00000",-0.27101,-0.10912,9.67305,0.13105,0.01338,0.11071,0.04507,0.10156,1.39400
31,"5,926.00000",017245,TRUSTCO BANK CORP/NY,TRST,TRUSTCO BANK CORP NY,TRST,"6,035.00000","77,519.00000",-0.01339,0.18009,8.73175,0.09701,0.00993,0.19680,0.04800,0.04994,1.06503
32,"6,137.00000",008898,RAYMOND JAMES FINANCIAL INC,RJF,RAYMOND JAMES FINANCIAL INC,RJF,"6,211.00000","69,649.00000",-0.13296,0.06272,11.03313,0.13322,0.02267,0.30421,0.06020,0.30346,2.30268
33,"6,185.00000",011770,STIFEL FINANCIAL CORP,SF,STIFEL FINANCIAL CORP,SF,"6,211.00000","72,996.00000",-0.18003,0.02630,10.43558,0.12775,0.02423,0.08125,0.09146,0.27986,1.69170
34,"6,281.00000",015199,1ST SOURCE CORP,SRCE,1ST SOURCE CORP,SRCE,"6,020.00000","36,346.00000",-0.08362,0.10301,8.99916,0.11317,0.01464,0.06487,0.04340,0.10659,1.33926
35,"6,407.00000",004885,FRANKLIN RESOURCES INC,BEN,FRANKLIN RESOURCES INC,BEN,"6,282.00000","37,584.00000",-0.03929,0.20438,10.09280,0.46438,0.07577,0.19228,0.31400,0.19522,1.32881
36,"6,736.00000",017195,FIRST FINL BANCORP INC/OH,FFBC,FIRST FINANCIAL BANCORP OHIO,FFBC,"6,020.00000","35,685.00000",-0.07867,0.13831,9.70071,0.13834,0.01256,0.02663,0.04737,0.02229,1.01612
37,"6,827.00000",017184,SEACOAST BANKING CORP/FL,SBCF,SEACOAST BANKING CORP FLA,SBCF,"6,020.00000","69,586.00000",-0.33563,-0.19129,9.17797,0.13539,0.01285,0.07620,0.02392,0.16051,1.57961
38,"6,944.00000",016832,GLACIER BANCORP INC,GBCI,GLACIER BANCORP INC NEW,GBCI,"6,020.00000","87,952.00000",-0.22160,-0.06643,10.16357,0.12250,0.01098,0.01687,0.04801,0.40188,1.97506
39,"7,067.00000",017095,OLD NATIONAL BANCORP,ONB,OLD NATIONAL BANCORP,ONB,"6,020.00000","12,068.00000",-0.17829,0.00936,10.10453,0.12317,0.01135,0.03362,0.10843,0.06502,0.99766
40,"7,407.00000",017269,AMERISERV FINANCIAL INC/PA,ASRV,AMERISERV FINANCIAL INC,ASRV,"6,020.00000","92,807.00000",-0.25861,-0.11872,7.19711,0.08727,0.00530,0.03077,0.05454,0.04364,0.56574
41,"7,460.00000",019355,SIMMONS FIRST NATL CP -CL A,SFNC,SIMMONS 1ST NATIONAL CORP,SFNC,"6,020.00000","91,855.00000",-0.35856,-0.20174,10.11556,0.13140,0.01097,0.06684,0.07914,0.10577,1.02625
42,"7,720.00000",016890,INDEPENDENT BANK CORP/MI,IBCP,INDEPENDENT BANK CORP MICH,IBCP,"6,020.00000","88,912.00000",-0.22210,-0.04963,8.45633,0.08470,0.01337,0.02327,0.02456,0.11911,1.26819
43,"7,784.00000",014219,CADENCE BANK,CADE,CADENCE BANK,CADE,"6,020.00000","85,789.00000",-0.31284,-0.14262,10.77205,0.10659,0.00409,0.02716,0.03702,0.97954,1.10423
44,"7,788.00000",016989,PEOPLES BANCORP NC INC,PEBK,PEOPLES BANCORP NC INC NEW,PEBK,"6,020.00000","90,983.00000",0.15601,0.32665,7.39277,0.08766,0.00932,0.17085,0.03524,0.14796,1.09725
45,"7,871.00000",016790,COMMUNITY FINANCIAL SYST INC,CBU,COMMUNITY BANK SYSTEM INC,CBU,"6,020.00000","86,896.00000",-0.25437,-0.12401,9.65199,0.13508,0.01220,0.12056,0.02332,0.11640,1.91014
46,"8,087.00000",012138,PRICE (T. ROWE) GROUP,TROW,T ROWE PRICE GROUP INC,TROW,"6,282.00000","10,138.00000",-0.17776,-0.00799,9.43420,0.72130,0.24645,0.12984,0.02894,0.17356,4.99462
47,"8,179.00000",016889,INDEPENDENT BANK CORP/MA,INDB,INDEPENDENT BANK CORP MA,INDB,"6,020.00000","10,252.00000",-0.21046,-0.04734,9.92444,0.14779,0.00592,0.10971,0.01059,0.54672,1.27895
48,"8,228.00000",017240,TOMPKINS FINANCIAL CORP,TMP,TOMPKINS FINANCIAL CORP,TMP,"6,020.00000","10,308.00000",-0.13701,0.02749,8.96444,0.09303,0.01141,0.00807,0.02440,0.02595,1.67429
49,"8,534.00000",018049,F N B CORP/FL,FNB,F N B CORP PA,FNB,"6,020.00000","10,629.00000",-0.09169,0.12909,10.58439,0.12763,0.01024,0.08840,0.06020,0.05780,0.76713

In [46]:
# =========================================================
# Cell 17. 회귀분석용 데이터 정리
# =========================================================

main_y = "vw_adj_cum_ret_202203_202303"

y_vars = [
    "raw_cum_ret_202203_202303",
    "ew_adj_cum_ret_202203_202303",
    "vw_adj_cum_ret_202203_202303",
    "max_drawdown_202203_202303",
    "raw_cum_ret_202203_202307",
    "ew_adj_cum_ret_202203_202307",
    "vw_adj_cum_ret_202203_202307",
    "max_drawdown_202203_202307",
    "raw_cum_ret_202303",
    "ew_adj_cum_ret_202303",
    "vw_adj_cum_ret_202303",
    "max_drawdown_202303"
]

id_cols = [
    "PERMCO", "gvkey", "conm", "tic", "COMNAM", "TICKER",
    "cusip8", "representative_cusip_202203_202303",
    "representative_permno_202203_202303",
    "sich_num", "naicsh", "SICCD", "NAICS"
]

existing_id_cols = [c for c in id_cols if c in analysis_df.columns]
existing_y_vars = [c for c in y_vars if c in analysis_df.columns]

reg_cols = existing_id_cols + existing_y_vars + x_vars_extended

reg_df = analysis_df[reg_cols].copy()
reg_df = reg_df.replace([np.inf, -np.inf], np.nan)

# 숫자형 변환
for col in existing_y_vars + x_vars_extended:
    if col in reg_df.columns:
        reg_df[col] = pd.to_numeric(reg_df[col], errors="coerce")

# winsorize
for col in existing_y_vars + x_vars_extended:
    if col in reg_df.columns:
        reg_df[col] = winsorize_series(reg_df[col], 0.01, 0.99)

# 메인 회귀 표본
reg_main = reg_df.dropna(subset=[main_y] + x_vars_main).copy()

print("reg_df shape:", reg_df.shape)
print("reg_main shape:", reg_main.shape)
print("Unique PERMCO in reg_main:", reg_main["PERMCO"].nunique())
print("Unique gvkey in reg_main:", reg_main["gvkey"].nunique())

print("\nMissing counts:")
display(reg_df[[main_y] + x_vars_main].isna().sum())

print("\nSummary statistics:")
display(reg_main[[main_y] + x_vars_main].describe().T)

print("\nCorrelation matrix:")
display(reg_main[[main_y] + x_vars_main].corr())

reg_df shape: (345, 34)
reg_main shape: (336, 34)
Unique PERMCO in reg_main: 336
Unique gvkey in reg_main: 336

Missing counts:

vw_adj_cum_ret_202203_202303    0
size                            7
equity_ratio                    7
roa                             7
cash_ratio                      7
debt_ratio                      7
asset_growth                    8
market_to_book                  8
dtype: int64

Summary statistics:

                                 count     mean     std      min      25%      50%     75%      max
vw_adj_cum_ret_202203_202303 336.00000 -0.05043 0.20415 -0.75413 -0.18053 -0.04839 0.07535  0.40138
size                         336.00000  8.91627 1.66781  6.24381  7.69725  8.63320 9.73148 14.37665
equity_ratio                 336.00000  0.10723 0.03941  0.05870  0.08827  0.10105 0.11702  0.42227
roa                          336.00000  0.01264 0.00784 -0.00075  0.00937  0.01159 0.01413  0.06581
cash_ratio                   336.00000  0.10954 0.07982  0.00895  0.04692  0.09014 0.14841  0.35697
debt_ratio                   336.00000  0.05173 0.05347  0.00050  0.02198  0.03596 0.06127  0.34349
asset_growth                 336.00000  0.15026 0.19514 -0.06924  0.04761  0.09871 0.17606  1.18327
market_to_book               336.00000  1.38901 0.65511  0.68879  1.05071  1.21058 1.45542  4.82887

Correlation matrix:

                              vw_adj_cum_ret_202203_202303     size  equity_ratio      roa  cash_ratio  debt_ratio  asset_growth  market_to_book
vw_adj_cum_ret_202203_202303                       1.00000 -0.12309       0.12327  0.10357     0.20304    -0.06176      -0.13692        -0.14559
size                                              -0.12309  1.00000      -0.01509  0.16604     0.12573     0.28974      -0.05044         0.22622
equity_ratio                                       0.12327 -0.01509       1.00000  0.70686     0.00683     0.14765      -0.02343         0.18091
roa                                                0.10357  0.16604       0.70686  1.00000     0.05156     0.22523      -0.16153         0.41178
cash_ratio                                         0.20304  0.12573       0.00683  0.05156     1.00000    -0.01698       0.23500         0.14670
debt_ratio                                        -0.06176  0.28974       0.14765  0.22523    -0.01698     1.00000      -0.12227         0.11494
asset_growth                                      -0.13692 -0.05044      -0.02343 -0.16153     0.23500    -0.12227       1.00000         0.14728
market_to_book                                    -0.14559  0.22622       0.18091  0.41178     0.14670     0.11494       0.14728         1.00000

In [47]:
# =========================================================
# Cell 18. 표본 진단표 생성
# =========================================================

sample_diagnostics = pd.DataFrame([
    {
        "step": "Raw CRSP-FRB Link file",
        "N_PERMCO": bank_permco_link_all["PERMCO"].nunique(),
        "N_rows": len(bank_permco_link_all)
    },
    {
        "step": "CRSP-FRB links active during 2021-2023",
        "N_PERMCO": bank_permco_link_filtered["PERMCO"].nunique(),
        "N_rows": len(bank_permco_link_filtered)
    },
    {
        "step": "One row per active PERMCO bank list",
        "N_PERMCO": len(bank_permcos),
        "N_rows": len(bank_permco_list_raw)
    },
    {
        "step": "CRSP bank PERMCOs with monthly return data",
        "N_PERMCO": permco_monthly["PERMCO"].nunique(),
        "N_rows": len(permco_monthly)
    },
    {
        "step": "PERMCOs with main-period Y variable",
        "N_PERMCO": y_main["PERMCO"].nunique(),
        "N_rows": len(y_main)
    },
    {
        "step": "PERMCOs matched to Compustat 2021 accounting data",
        "N_PERMCO": permco_x["PERMCO"].nunique(),
        "N_rows": len(permco_x)
    },
    {
        "step": "Final main regression sample",
        "N_PERMCO": reg_main["PERMCO"].nunique(),
        "N_rows": len(reg_main)
    }
])

print("Sample diagnostics:")
display(sample_diagnostics)

print("\nInstitution type distribution in active CRSP-FRB links:")
inst_type_active = (
    bank_permco_link_filtered["inst_type"]
    .value_counts(dropna=False)
    .reset_index()
)
inst_type_active.columns = ["inst_type", "N"]
display(inst_type_active)

print("\nSIC distribution in final regression sample:")
if "sich_num" in reg_main.columns:
    sic_distribution = reg_main["sich_num"].value_counts(dropna=False).sort_index().reset_index()
    sic_distribution.columns = ["sich_num", "N"]
    display(sic_distribution)

print("\nFinal sample firms, first 30 by dependent variable:")
display(
    reg_main[
        ["PERMCO", "gvkey", "conm", "tic", "COMNAM", "TICKER", "sich_num", main_y] + x_vars_main
    ].sort_values(main_y).head(30)
)

print("\nTop performers:")
display(
    reg_main[
        ["PERMCO", "gvkey", "conm", "tic", "COMNAM", "TICKER", "sich_num", main_y, "raw_cum_ret_202203_202303"] + x_vars_main
    ].sort_values(main_y, ascending=False).head(20)
)

print("\nWorst performers:")
display(
    reg_main[
        ["PERMCO", "gvkey", "conm", "tic", "COMNAM", "TICKER", "sich_num", main_y, "raw_cum_ret_202203_202303"] + x_vars_main
    ].sort_values(main_y, ascending=True).head(20)
)

Sample diagnostics:

                                                step  N_PERMCO  N_rows
0                             Raw CRSP-FRB Link file      1450    1495
1             CRSP-FRB links active during 2021-2023       394     395
2                One row per active PERMCO bank list       394     394
3         CRSP bank PERMCOs with monthly return data       362    5898
4                PERMCOs with main-period Y variable       345     345
5  PERMCOs matched to Compustat 2021 accounting data       354     354
6                       Final main regression sample       336     336

Institution type distribution in active CRSP-FRB links:

                 inst_type    N
0     Bank Holding Company  320
1   Thrift Holding Company   32
2   Thrift holding company   24
3          Commercial Bank    6
4          Non Member Bank    5
5    Domestic Entity Other    2
6     Bank holding company    2
7                      NaN    1
8   Thirft Holding Company    1
9                      FSB    1
10                National    1

SIC distribution in final regression sample:

      sich_num    N
0  6,020.00000  279
1  6,035.00000   21
2  6,036.00000   14
3  6,141.00000    5
4  6,162.00000    1
5  6,172.00000    1
6  6,199.00000    2
7  6,211.00000    4
8  6,282.00000    5
9  6,311.00000    1
10 6,331.00000    1
11 6,361.00000    1
12 7,389.00000    1

Final sample firms, first 30 by dependent variable:

          PERMCO   gvkey                          conm    tic                           COMNAM TICKER    sich_num  vw_adj_cum_ret_202203_202303     size  equity_ratio      roa  cash_ratio  debt_ratio  asset_growth  market_to_book
199 44,999.00000  160776             SIGNATURE BANK/NY   SBNY      SIGNATURE BANK NEW YORK N Y   SBNY 6,020.00000                      -0.75413 11.68221       0.06620  0.00775     0.25008     0.03051       0.60303         2.50142
243 53,609.00000  014275           FIRST REPUBLIC BANK   FRCB      FIRST REPUBLIC BANK S F NEW    FRC 6,020.00000                      -0.75413 12.10673       0.06773  0.00816     0.07150     0.03800       0.27077         3.02185
331 56,932.00000  034446       SILVERGATE CAPITAL CORP   SICP          SILVERGATE CAPITAL CORP     SI 6,020.00000                      -0.75413  9.68069       0.10052  0.00491     0.33663     0.00132       1.18327         2.80061
66   9,999.00000  018040    REPUBLIC FIRST BANCORP INC  FRBKQ       REPUBLIC FIRST BANCORP INC   FRBK 6,020.00000                      -0.67606  8.63527       0.05870  0.00447     0.02113     0.01654       0.11073         0.68879
272 55,109.00000  020677          FIRST FOUNDATION INC   FFWM             FIRST FOUNDATION INC   FFWM 6,020.00000                      -0.63441  9.22977       0.10436  0.01074     0.11002     0.02263       0.46557         1.31845
259 54,408.00000  170396         CUSTOMERS BANCORP INC   CUBI            CUSTOMERS BANCORP INC   CUBI 6,020.00000                      -0.59259  9.88201       0.06275  0.01607     0.02646     0.06101       0.06160         1.75145
257 54,332.00000  162293        FIRST INTERNET BANCORP   INBK           FIRST INTERNET BANCORP   INBK 6,020.00000                      -0.58951  8.34545       0.09032  0.01143     0.10519     0.14703      -0.00828         1.20637
296 56,141.00000  032519       METROPOLITAN BANK HLDNG    MCB   METROPOLITAN BANK HOLDING CORP    MCB 6,020.00000                      -0.58492  8.87015       0.07827  0.00851     0.33154     0.01093       0.64319         2.08876
252 54,001.00000  018948             MECHANICS BANCORP   MCHB                   HOMESTREET INC   HMST 6,020.00000                      -0.54871  9.87421       0.12294  0.01061     0.05155     0.00324       0.01462         0.75283
274 55,129.00000  019647              LENDINGCLUB CORP     LC                 LENDINGCLUB CORP     LC 6,141.00000                      -0.50554  8.49706       0.17351  0.00379     0.15582     0.14324       1.18327         2.87359
276 55,361.00000  020299       LIVE OAK BANCSHARES INC    LOB          LIVE OAK BANCSHARES INC    LOB 6,020.00000                      -0.50178  9.01352       0.08707  0.02033     0.02539     0.03905       0.04333         4.82887
212 46,890.00000  163920      WESTERN ALLIANCE BANCORP    WAL  WESTERN ALLIANCE BANCORPORATION    WAL 6,020.00000                      -0.46161 10.93280       0.08338  0.01606     0.00922     0.04538       0.53541         2.45899
155 31,194.00000  061586   IMPAC MORTGAGE HOLDINGS INC   IMPM      IMPAC MORTGAGE HOLDINGS INC    IMH 6,162.00000                      -0.45048  7.61222       0.05870 -0.00075     0.01741     0.34349      -0.06924         2.38848
27   5,057.00000  011687       ZIONS BANCORPORATION NA   ZION         ZIONS BANCORPORATION N A   ZION 6,020.00000                      -0.43729 11.44250       0.07535  0.01211     0.13960     0.02293       0.14385         1.36361
275 55,170.00000  022975        FIRST NORTHWEST BANCRP   FNWB          FIRST NORTHWEST BANCORP   FNWB 6,020.00000                      -0.41122  7.56064       0.09940  0.00803     0.06560     0.06612       0.16123         0.98217
271 55,085.00000  021633          VERITEX HOLDINGS INC   VBTX             VERITEX HOLDINGS INC   VBTX 6,020.00000                      -0.39967  9.18577       0.13478  0.01431     0.04941     0.10530       0.10615         1.49346
8    1,261.00000  003231                  COMERICA INC    CMA                     COMERICA INC    CMA 6,020.00000                      -0.39178 11.45758       0.07930  0.01234     0.23970     0.03331       0.07361         1.51537
98  13,294.00000  030647  PATRIOT NATIONAL BANCORP INC   PNBK     PATRIOT NATIONAL BANCORP INC   PNBK 6,020.00000                      -0.36739  6.85486       0.07100  0.00537     0.04960     0.13030       0.07693         0.91346
301 56,179.00000  144122            MVB FINANCIAL CORP   MVBF             M V B FINANCIAL CORP   MVBF 6,020.00000                      -0.35122  7.93467       0.09824  0.01401     0.11107     0.03689       0.19772         1.82939
200 45,559.00000  125580     SOUTHERN FIRST BANKSHARES   SFST    SOUTHERN FIRST BANCSHARES INC   SFST 6,020.00000                      -0.34848  7.98124       0.09499  0.01597     0.05715     0.02192       0.17843         1.78227
247 53,687.00000  005072            ALLY FINANCIAL INC   ALLY               ALLY FINANCIAL INC   ALLY 6,172.00000                      -0.33022 12.11239       0.08086  0.01680     0.03317     0.09447      -0.00028         1.09258
18   2,535.00000  009783                       KEYCORP    KEY                      KEYCORP NEW    KEY 6,020.00000                      -0.32528 12.13536       0.08330  0.01409     0.06398     0.07233       0.09399         1.38403
62   9,389.00000  018533           HORIZON BANCORP INC   HBNC              HORIZON BANCORP INC   HBNC 6,020.00000                      -0.32029  8.90584       0.09806  0.01181     0.08113     0.10753       0.25283         1.25548
328 56,887.00000  018434         ALERUS FINANCIAL CORP   ALRS            ALERUS FINANCIAL CORP   ALRS 6,020.00000                      -0.31839  8.12938       0.10593  0.01553     0.07142     0.01863       0.12573         1.40232
246 53,647.00000  185824                BANKUNITED INC    BKU                   BANKUNITED INC    BKU 6,020.00000                      -0.31683 10.48613       0.08482  0.01159     0.00895     0.08139       0.02299         1.19291
107 14,751.00000  017724        CONNECTONE BANCORP INC   CNOB       CONNECTONE BANCORP INC NEW   CNOB 6,020.00000                      -0.31539  9.00325       0.12464  0.01603     0.03266     0.07793       0.07713         1.27730
106 14,531.00000  062654      SANDY SPRING BANCORP INC   SASR         SANDY SPRING BANCORP INC   SASR 6,020.00000                      -0.31129  9.44072       0.12070  0.01867     0.03336     0.03026      -0.01623         1.42749
126 16,037.00000  066504           COLONY BANKCORP INC   CBAN              COLONY BANKCORP INC   CBAN 6,020.00000                      -0.31107  7.89793       0.08088  0.00693     0.07327     0.03311       0.52594         1.07215
180 41,698.00000  065050           GLEN BURNIE BANCORP   GLBZ              GLEN BURNIE BANCORP   GLBZ 6,020.00000                      -0.30276  6.24381       0.08079  0.00569     0.14066     0.04637       0.05383         1.11871
335 57,369.00000  036633        EASTERN BANKSHARES INC    EBC           EASTERN BANKSHARES INC    EBC 6,020.00000                      -0.29614 10.06527       0.14488  0.00658     0.05239     0.00526       0.47280         1.01866

Top performers:

          PERMCO   gvkey                          conm    tic                            COMNAM TICKER    sich_num  vw_adj_cum_ret_202203_202303  raw_cum_ret_202203_202303     size  equity_ratio     roa  cash_ratio  debt_ratio  asset_growth  market_to_book
290 55,987.00000  031606        ESQUIRE FINCL HOLD INC    ESQ        ESQUIRE FINANCIAL HOLDINGS    ESQ 6,020.00000                       0.40138                    0.16918  7.07223       0.12194 0.01521     0.16918     0.00253       0.25841         1.77273
50   8,674.00000  004690  FIRST CITIZENS BANCSH  -CL A  FCNCA  FIRST CITIZENS BANCSHARES INC NC  FCNCA 6,020.00000                       0.40138                    0.22487 10.97350       0.07541 0.00939     0.16211     0.03169       0.16715         1.85243
236 53,116.00000  066158            OAK VALLEY BANCORP   OVLY                OAK VALLEY BANCORP   OVLY 6,020.00000                       0.40138                    0.22487  7.58298       0.07260 0.00832     0.35697     0.00380       0.29971         1.00524
222 51,209.00000  174301         LIMESTONE BANCORP INC   LMST             LIMESTONE BANCORP INC   LMST 6,020.00000                       0.40138                    0.20798  7.25537       0.09251 0.01053     0.05482     0.05038       0.07879         1.08219
61   9,280.00000  016781               CITY HOLDING CO   CHCO                   CITY HOLDING CO   CHCO 6,020.00000                       0.38391                    0.17295  8.70013       0.11345 0.01467     0.10571     0.05204       0.04255         1.80871
334 57,031.00000  023552     PROFESSIONAL HOLDING CORP   PFHD         PROFESSIONAL HOLDING CORP   PFHD 6,020.00000                       0.37020                    0.22487  7.88763       0.08690 0.00802     0.22427     0.01882       0.29497         1.11274
143 17,665.00000  107325            MACATAWA BANK CORP   MCBC                MACATAWA BANK CORP   MCBC 6,020.00000                       0.35600                    0.14885  7.98233       0.08673 0.00991     0.35697     0.02932       0.10852         1.18963
139 16,640.00000  117026     GREENE COUNTY BANCORP INC   GCBC         GREENE COUNTY BANCORP INC   GCBC 6,035.00000                       0.34865                    0.12349  7.69636       0.06798 0.01088     0.07014     0.01116       0.31222         1.60034
109 14,781.00000  025201  CASS INFORMATION SYSTEMS INC   CASS      CASS INFORMATION SYSTEMS INC   CASS 7,389.00000                       0.33257                    0.13529  7.84577       0.09621 0.01120     0.21102     0.00191       0.15961         2.19701
44   7,788.00000  016989        PEOPLES BANCORP NC INC   PEBK        PEOPLES BANCORP NC INC NEW   PEBK 6,020.00000                       0.32665                    0.15601  7.39277       0.08766 0.00932     0.17085     0.03524       0.14796         1.09725
152 28,947.00000  023450          NORTHRIM BANCORP INC   NRIM              NORTHRIM BANCORP INC   NRIM 6,020.00000                       0.31743                    0.11093  7.91012       0.08728 0.01377     0.23703     0.01313       0.28416         1.09921
213 47,422.00000  164708      AMERIPRISE FINANCIAL INC    AMP          AMERIPRISE FINANCIAL INC    AMP 6,282.00000                       0.30142                    0.03946 12.07812       0.05870 0.01568     0.06782     0.03146       0.06086         4.82887
292 56,029.00000  027345         PRINCETON BANCORP INC   BPRN             PRINCETON BANCORP INC   BPRN 6,020.00000                       0.30131                    0.10084  7.43111       0.12833 0.01332     0.09404     0.01100       0.05293         0.87755
77  11,480.00000  019570             S & T BANCORP INC   STBA                 S & T BANCORP INC   STBA 6,020.00000                       0.29745                    0.04973  9.15784       0.12715 0.01163     0.09719     0.02228       0.05806         1.02809
311 56,481.00000  033625    AMALGAMATED FINANCIAL CORP   AMAL        AMALGAMATED FINANCIAL CORP   AMAL 6,020.00000                       0.29432                    0.04700  8.86473       0.07965 0.00748     0.07905     0.01865       0.18386         0.92604
112 15,307.00000  020109     CAPITAL CITY BK GROUP INC   CCBG           CAPITAL CITY BANK GROUP   CCBG 6,020.00000                       0.29031                    0.07443  8.35793       0.08986 0.00783     0.24282     0.02357       0.12264         1.16385
83  12,058.00000  028022             BANCFIRST CORP/OK   BANF                    BANCFIRST CORP   BANF 6,020.00000                       0.28563                    0.08712  9.14906       0.12458 0.01782     0.21804     0.00966       0.02098         1.96330
269 55,027.00000  139705         MIDDLEFIELD BANC CORP   MBCN             MIDDLEFIELD BANC CORP   MBCN 6,020.00000                       0.28135                    0.14006  7.19369       0.10919 0.01400     0.08978     0.01035      -0.04380         1.00490
123 15,993.00000  066155        NORWOOD FINANCIAL CORP   NWFL            NORWOOD FINANCIAL CORP   NWFL 6,020.00000                       0.28106                    0.08809  7.63458       0.09923 0.01204     0.09992     0.04612       0.11698         1.03840
340 58,670.00000  116675     ORANGE COUNTY BANCORP INC    OBT         ORANGE COUNTY BANCORP INC    OBT 6,020.00000                       0.27547                    0.10230  7.66977       0.08533 0.00994     0.14290     0.01186       0.28689         1.23940

Worst performers:

          PERMCO   gvkey                          conm    tic                           COMNAM TICKER    sich_num  vw_adj_cum_ret_202203_202303  raw_cum_ret_202203_202303     size  equity_ratio      roa  cash_ratio  debt_ratio  asset_growth  market_to_book
199 44,999.00000  160776             SIGNATURE BANK/NY   SBNY      SIGNATURE BANK NEW YORK N Y   SBNY 6,020.00000                      -0.75413                   -0.86465 11.68221       0.06620  0.00775     0.25008     0.03051       0.60303         2.50142
243 53,609.00000  014275           FIRST REPUBLIC BANK   FRCB      FIRST REPUBLIC BANK S F NEW    FRC 6,020.00000                      -0.75413                   -0.86465 12.10673       0.06773  0.00816     0.07150     0.03800       0.27077         3.02185
331 56,932.00000  034446       SILVERGATE CAPITAL CORP   SICP          SILVERGATE CAPITAL CORP     SI 6,020.00000                      -0.75413                   -0.86465  9.68069       0.10052  0.00491     0.33663     0.00132       1.18327         2.80061
66   9,999.00000  018040    REPUBLIC FIRST BANCORP INC  FRBKQ       REPUBLIC FIRST BANCORP INC   FRBK 6,020.00000                      -0.67606                   -0.73796  8.63527       0.05870  0.00447     0.02113     0.01654       0.11073         0.68879
272 55,109.00000  020677          FIRST FOUNDATION INC   FFWM             FIRST FOUNDATION INC   FFWM 6,020.00000                      -0.63441                   -0.71338  9.22977       0.10436  0.01074     0.11002     0.02263       0.46557         1.31845
259 54,408.00000  170396         CUSTOMERS BANCORP INC   CUBI            CUSTOMERS BANCORP INC   CUBI 6,020.00000                      -0.59259                   -0.69911  9.88201       0.06275  0.01607     0.02646     0.06101       0.06160         1.75145
257 54,332.00000  162293        FIRST INTERNET BANCORP   INBK           FIRST INTERNET BANCORP   INBK 6,020.00000                      -0.58951                   -0.65565  8.34545       0.09032  0.01143     0.10519     0.14703      -0.00828         1.20637
296 56,141.00000  032519       METROPOLITAN BANK HLDNG    MCB   METROPOLITAN BANK HOLDING CORP    MCB 6,020.00000                      -0.58492                   -0.66856  8.87015       0.07827  0.00851     0.33154     0.01093       0.64319         2.08876
252 54,001.00000  018948             MECHANICS BANCORP   MCHB                   HOMESTREET INC   HMST 6,020.00000                      -0.54871                   -0.63426  9.87421       0.12294  0.01061     0.05155     0.00324       0.01462         0.75283
274 55,129.00000  019647              LENDINGCLUB CORP     LC                 LENDINGCLUB CORP     LC 6,141.00000                      -0.50554                   -0.61195  8.49706       0.17351  0.00379     0.15582     0.14324       1.18327         2.87359
276 55,361.00000  020299       LIVE OAK BANCSHARES INC    LOB          LIVE OAK BANCSHARES INC    LOB 6,020.00000                      -0.50178                   -0.61759  9.01352       0.08707  0.02033     0.02539     0.03905       0.04333         4.82887
212 46,890.00000  163920      WESTERN ALLIANCE BANCORP    WAL  WESTERN ALLIANCE BANCORPORATION    WAL 6,020.00000                      -0.46161                   -0.61357 10.93280       0.08338  0.01606     0.00922     0.04538       0.53541         2.45899
155 31,194.00000  061586   IMPAC MORTGAGE HOLDINGS INC   IMPM      IMPAC MORTGAGE HOLDINGS INC    IMH 6,162.00000                      -0.45048                   -0.56212  7.61222       0.05870 -0.00075     0.01741     0.34349      -0.06924         2.38848
27   5,057.00000  011687       ZIONS BANCORPORATION NA   ZION         ZIONS BANCORPORATION N A   ZION 6,020.00000                      -0.43729                   -0.56493 11.44250       0.07535  0.01211     0.13960     0.02293       0.14385         1.36361
275 55,170.00000  022975        FIRST NORTHWEST BANCRP   FNWB          FIRST NORTHWEST BANCORP   FNWB 6,020.00000                      -0.41122                   -0.48776  7.56064       0.09940  0.00803     0.06560     0.06612       0.16123         0.98217
271 55,085.00000  021633          VERITEX HOLDINGS INC   VBTX             VERITEX HOLDINGS INC   VBTX 6,020.00000                      -0.39967                   -0.53875  9.18577       0.13478  0.01431     0.04941     0.10530       0.10615         1.49346
8    1,261.00000  003231                  COMERICA INC    CMA                     COMERICA INC    CMA 6,020.00000                      -0.39178                   -0.52075 11.45758       0.07930  0.01234     0.23970     0.03331       0.07361         1.51537
98  13,294.00000  030647  PATRIOT NATIONAL BANCORP INC   PNBK     PATRIOT NATIONAL BANCORP INC   PNBK 6,020.00000                      -0.36739                   -0.46545  6.85486       0.07100  0.00537     0.04960     0.13030       0.07693         0.91346
301 56,179.00000  144122            MVB FINANCIAL CORP   MVBF             M V B FINANCIAL CORP   MVBF 6,020.00000                      -0.35122                   -0.45163  7.93467       0.09824  0.01401     0.11107     0.03689       0.19772         1.82939
200 45,559.00000  125580     SOUTHERN FIRST BANKSHARES   SFST    SOUTHERN FIRST BANCSHARES INC   SFST 6,020.00000                      -0.34848                   -0.46197  7.98124       0.09499  0.01597     0.05715     0.02192       0.17843         1.78227

In [48]:
# =========================================================
# Cell 19. OLS 회귀분석 함수
# =========================================================

def run_ols(df, y_col, x_cols, model_name):
    temp = df.dropna(subset=[y_col] + x_cols).copy()

    y = temp[y_col]
    X = temp[x_cols]
    X = sm.add_constant(X)

    model = sm.OLS(y, X).fit(cov_type="HC3")

    table = pd.DataFrame({
        "model": model_name,
        "y": y_col,
        "variable": model.params.index,
        "coef": model.params.values,
        "std_err": model.bse.values,
        "t_stat": model.tvalues.values,
        "p_value": model.pvalues.values
    })

    table["stars"] = table["p_value"].apply(make_stars)
    table["coef_stars"] = table["coef"].map(lambda x: f"{x:.4f}") + table["stars"]
    table["t_line"] = table["t_stat"].map(lambda x: f"({x:.2f})")

    fit = {
        "model": model_name,
        "y": y_col,
        "N": int(model.nobs),
        "R2": model.rsquared,
        "Adj_R2": model.rsquared_adj,
        "F_pvalue": model.f_pvalue
    }

    return model, table, fit


def make_regression_wide_table(ols_tables, fit_df=None):
    temp = ols_tables.copy()

    coef_wide = temp.pivot(index="variable", columns="model", values="coef_stars")
    t_wide = temp.pivot(index="variable", columns="model", values="t_line")

    rows = []
    for var in coef_wide.index:
        rows.append(pd.DataFrame(coef_wide.loc[[var]]))
        t_row = pd.DataFrame(t_wide.loc[[var]])
        t_row.index = [var + "_t"]
        rows.append(t_row)

    out = pd.concat(rows)

    if fit_df is not None and len(fit_df) > 0:
        for stat in ["N", "R2", "Adj_R2"]:
            stat_row = {}
            for _, row in fit_df.iterrows():
                m = row["model"]
                if stat == "N":
                    stat_row[m] = f"{int(row[stat])}"
                else:
                    stat_row[m] = f"{row[stat]:.4f}"
            out.loc[stat] = pd.Series(stat_row)

    return out


print("OLS functions ready.")

OLS functions ready.

In [49]:
# =========================================================
# Cell 20. Main Regression
# =========================================================

x_model1 = ["size", "equity_ratio", "roa"]

x_model2 = [
    "size",
    "equity_ratio",
    "roa",
    "cash_ratio",
    "debt_ratio",
    "asset_growth"
]

x_model3 = [
    "size",
    "equity_ratio",
    "roa",
    "cash_ratio",
    "debt_ratio",
    "asset_growth",
    "market_to_book"
]

ols1, ols_table1, fit1 = run_ols(reg_main, main_y, x_model1, "M1_basic")
ols2, ols_table2, fit2 = run_ols(reg_main, main_y, x_model2, "M2_balance_sheet")
ols3, ols_table3, fit3 = run_ols(reg_main, main_y, x_model3, "M3_full")

print("\n===== M1_basic =====")
print(ols1.summary())

print("\n===== M2_balance_sheet =====")
print(ols2.summary())

print("\n===== M3_full =====")
print(ols3.summary())

ols_tables = pd.concat([ols_table1, ols_table2, ols_table3], ignore_index=True)
ols_fit = pd.DataFrame([fit1, fit2, fit3])

main_regression_table_wide = make_regression_wide_table(ols_tables, ols_fit)

print("\nMain regression table, wide format:")
display(main_regression_table_wide)

display(ols_fit)

===== M1_basic =====
                                 OLS Regression Results
========================================================================================
Dep. Variable:     vw_adj_cum_ret_202203_202303   R-squared:                       0.033
Model:                                      OLS   Adj. R-squared:                  0.024
Method:                           Least Squares   F-statistic:                     4.236
Date:                          Wed, 27 May 2026   Prob (F-statistic):            0.00589
Time:                                  17:09:29   Log-Likelihood:                 63.238
No. Observations:                           336   AIC:                            -118.5
Df Residuals:                               332   BIC:                            -103.2
Df Model:                                     3
Covariance Type:                            HC3
================================================================================
                   coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------
const            0.0353      0.070      0.505      0.614      -0.102       0.172
size            -0.0166      0.007     -2.254      0.024      -0.031      -0.002
equity_ratio     0.3324      0.401      0.829      0.407      -0.454       1.119
roa              2.1026      1.901      1.106      0.269      -1.623       5.828
==============================================================================
Omnibus:                       11.495   Durbin-Watson:                   1.871
Prob(Omnibus):                  0.003   Jarque-Bera (JB):               13.782
Skew:                          -0.329   Prob(JB):                      0.00102
Kurtosis:                       3.742   Cond. No.                     1.72e+03
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)
[2] The condition number is large, 1.72e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

===== M2_balance_sheet =====
                                 OLS Regression Results
========================================================================================
Dep. Variable:     vw_adj_cum_ret_202203_202303   R-squared:                       0.121
Model:                                      OLS   Adj. R-squared:                  0.105
Method:                           Least Squares   F-statistic:                     6.380
Date:                          Wed, 27 May 2026   Prob (F-statistic):           2.27e-06
Time:                                  17:09:29   Log-Likelihood:                 79.271
No. Observations:                           336   AIC:                            -144.5
Df Residuals:                               329   BIC:                            -117.8
Df Model:                                     6
Covariance Type:                            HC3
================================================================================
                   coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------
const            0.0164      0.072      0.230      0.818      -0.124       0.157
size            -0.0185      0.007     -2.589      0.010      -0.033      -0.004
equity_ratio     0.5837      0.380      1.536      0.124      -0.161       1.328
roa              0.3783      1.712      0.221      0.825      -2.977       3.734
cash_ratio       0.6876      0.152      4.521      0.000       0.389       0.986
debt_ratio      -0.2252      0.277     -0.812      0.417      -0.769       0.319
asset_growth    -0.2197      0.091     -2.406      0.016      -0.399      -0.041
==============================================================================
Omnibus:                       10.407   Durbin-Watson:                   1.875
Prob(Omnibus):                  0.005   Jarque-Bera (JB):               13.007
Skew:                          -0.286   Prob(JB):                      0.00150
Kurtosis:                       3.776   Cond. No.                     1.77e+03
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)
[2] The condition number is large, 1.77e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

===== M3_full =====
                                 OLS Regression Results
========================================================================================
Dep. Variable:     vw_adj_cum_ret_202203_202303   R-squared:                       0.148
Model:                                      OLS   Adj. R-squared:                  0.129
Method:                           Least Squares   F-statistic:                     7.024
Date:                          Wed, 27 May 2026   Prob (F-statistic):           8.15e-08
Time:                                  17:09:29   Log-Likelihood:                 84.450
No. Observations:                           336   AIC:                            -152.9
Df Residuals:                               328   BIC:                            -122.4
Df Model:                                     7
Covariance Type:                            HC3
==================================================================================
                     coef    std err          z      P>|z|      [0.025      0.975]
----------------------------------------------------------------------------------
const              0.0496      0.070      0.705      0.481      -0.088       0.188
size              -0.0155      0.007     -2.293      0.022      -0.029      -0.002
equity_ratio       0.3607      0.340      1.059      0.289      -0.307       1.028
roa                3.2814      1.899      1.728      0.084      -0.441       7.003
cash_ratio         0.7108      0.146      4.874      0.000       0.425       0.997
debt_ratio        -0.2189      0.255     -0.859      0.390      -0.718       0.280
asset_growth      -0.1731      0.084     -2.052      0.040      -0.338      -0.008
market_to_book    -0.0596      0.028     -2.138      0.033      -0.114      -0.005
==============================================================================
Omnibus:                        8.672   Durbin-Watson:                   1.884
Prob(Omnibus):                  0.013   Jarque-Bera (JB):               12.947
Skew:                          -0.160   Prob(JB):                      0.00154
Kurtosis:                       3.907   Cond. No.                     1.96e+03
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)
[2] The condition number is large, 1.96e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

Main regression table, wide format:

model              M1_basic M2_balance_sheet    M3_full
asset_growth            NaN        -0.2197**  -0.1731**
asset_growth_t          NaN          (-2.41)    (-2.05)
cash_ratio              NaN        0.6876***  0.7108***
cash_ratio_t            NaN           (4.52)     (4.87)
const                0.0353           0.0164     0.0496
const_t              (0.50)           (0.23)     (0.70)
debt_ratio              NaN          -0.2252    -0.2189
debt_ratio_t            NaN          (-0.81)    (-0.86)
equity_ratio         0.3324           0.5837     0.3607
equity_ratio_t       (0.83)           (1.54)     (1.06)
market_to_book          NaN              NaN  -0.0596**
market_to_book_t        NaN              NaN    (-2.14)
roa                  2.1026           0.3783    3.2814*
roa_t                (1.11)           (0.22)     (1.73)
size              -0.0166**       -0.0185***  -0.0155**
size_t              (-2.25)          (-2.59)    (-2.29)
N                       336              336        336
R2                   0.0330           0.1210     0.1477
Adj_R2               0.0242           0.1049     0.1295

              model                             y    N      R2  Adj_R2  F_pvalue
0          M1_basic  vw_adj_cum_ret_202203_202303  336 0.03295 0.02421   0.00589
1  M2_balance_sheet  vw_adj_cum_ret_202203_202303  336 0.12097 0.10494   0.00000
2           M3_full  vw_adj_cum_ret_202203_202303  336 0.14766 0.12947   0.00000

In [50]:
# =========================================================
# Cell 21. Robustness Tests
# =========================================================

robust_specs = [
    ("R1_raw_return_main_period", "raw_cum_ret_202203_202303", x_model3),
    ("R2_ew_bank_adjusted_main_period", "ew_adj_cum_ret_202203_202303", x_model3),
    ("R3_extended_vw_adjusted_202203_202307", "vw_adj_cum_ret_202203_202307", x_model3),
    ("R4_march_2023_vw_adjusted", "vw_adj_cum_ret_202303", x_model3),
    ("R5_max_drawdown_main_period", "max_drawdown_202203_202303", x_model3),
]

robust_models = {}
robust_tables_list = []
robust_fits_list = []

for model_name, y_col, x_cols in robust_specs:
    if y_col not in reg_df.columns:
        print(f"{model_name}: missing y variable {y_col}. Skipped.")
        continue

    temp = reg_df.dropna(subset=[y_col] + x_cols).copy()

    if len(temp) < 30:
        print(f"{model_name}: sample too small. N={len(temp)}. Skipped.")
        continue

    model, table, fit = run_ols(temp, y_col, x_cols, model_name)

    robust_models[model_name] = model
    robust_tables_list.append(table)
    robust_fits_list.append(fit)

    print(f"\n===== {model_name} =====")
    print(model.summary())

if len(robust_tables_list) > 0:
    robust_ols_tables = pd.concat(robust_tables_list, ignore_index=True)
    robust_ols_fit = pd.DataFrame(robust_fits_list)
    robustness_table_wide = make_regression_wide_table(robust_ols_tables, robust_ols_fit)
else:
    robust_ols_tables = pd.DataFrame()
    robust_ols_fit = pd.DataFrame()
    robustness_table_wide = pd.DataFrame()

print("\nRobustness table, wide format:")
display(robustness_table_wide)

display(robust_ols_fit)

===== R1_raw_return_main_period =====
                                OLS Regression Results
=====================================================================================
Dep. Variable:     raw_cum_ret_202203_202303   R-squared:                       0.178
Model:                                   OLS   Adj. R-squared:                  0.161
Method:                        Least Squares   F-statistic:                     8.342
Date:                       Wed, 27 May 2026   Prob (F-statistic):           2.20e-09
Time:                               17:09:29   Log-Likelihood:                 128.00
No. Observations:                        336   AIC:                            -240.0
Df Residuals:                            328   BIC:                            -209.5
Df Model:                                  7
Covariance Type:                         HC3
==================================================================================
                     coef    std err          z      P>|z|      [0.025      0.975]
----------------------------------------------------------------------------------
const             -0.0220      0.063     -0.349      0.727      -0.146       0.102
size              -0.0242      0.006     -4.033      0.000      -0.036      -0.012
equity_ratio       0.3384      0.300      1.130      0.259      -0.249       0.926
roa                2.2172      1.713      1.294      0.196      -1.140       5.575
cash_ratio         0.6426      0.128      5.034      0.000       0.392       0.893
debt_ratio        -0.1678      0.232     -0.724      0.469      -0.622       0.287
asset_growth      -0.1721      0.075     -2.286      0.022      -0.320      -0.025
market_to_book    -0.0511      0.024     -2.108      0.035      -0.099      -0.004
==============================================================================
Omnibus:                        7.701   Durbin-Watson:                   1.851
Prob(Omnibus):                  0.021   Jarque-Bera (JB):               11.846
Skew:                          -0.103   Prob(JB):                      0.00268
Kurtosis:                       3.896   Cond. No.                     1.96e+03
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)
[2] The condition number is large, 1.96e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

===== R2_ew_bank_adjusted_main_period =====
                                 OLS Regression Results
========================================================================================
Dep. Variable:     ew_adj_cum_ret_202203_202303   R-squared:                       0.157
Model:                                      OLS   Adj. R-squared:                  0.139
Method:                           Least Squares   F-statistic:                     7.275
Date:                          Wed, 27 May 2026   Prob (F-statistic):           4.09e-08
Time:                                  17:09:29   Log-Likelihood:                 68.750
No. Observations:                           336   AIC:                            -121.5
Df Residuals:                               328   BIC:                            -90.96
Df Model:                                     7
Covariance Type:                            HC3
==================================================================================
                     coef    std err          z      P>|z|      [0.025      0.975]
----------------------------------------------------------------------------------
const              0.1543      0.074      2.086      0.037       0.009       0.299
size              -0.0200      0.007     -2.815      0.005      -0.034      -0.006
equity_ratio       0.3586      0.357      1.004      0.315      -0.341       1.058
roa                3.2091      2.019      1.590      0.112      -0.748       7.166
cash_ratio         0.7573      0.151      5.002      0.000       0.461       1.054
debt_ratio        -0.2638      0.273     -0.968      0.333      -0.798       0.271
asset_growth      -0.1861      0.089     -2.098      0.036      -0.360      -0.012
market_to_book    -0.0629      0.029     -2.156      0.031      -0.120      -0.006
==============================================================================
Omnibus:                        8.506   Durbin-Watson:                   1.868
Prob(Omnibus):                  0.014   Jarque-Bera (JB):               12.134
Skew:                          -0.177   Prob(JB):                      0.00232
Kurtosis:                       3.861   Cond. No.                     1.96e+03
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)
[2] The condition number is large, 1.96e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

===== R3_extended_vw_adjusted_202203_202307 =====
                                 OLS Regression Results
========================================================================================
Dep. Variable:     vw_adj_cum_ret_202203_202307   R-squared:                       0.122
Model:                                      OLS   Adj. R-squared:                  0.103
Method:                           Least Squares   F-statistic:                     5.561
Date:                          Wed, 27 May 2026   Prob (F-statistic):           4.60e-06
Time:                                  17:09:29   Log-Likelihood:                 58.668
No. Observations:                           333   AIC:                            -101.3
Df Residuals:                               325   BIC:                            -70.87
Df Model:                                     7
Covariance Type:                            HC3
==================================================================================
                     coef    std err          z      P>|z|      [0.025      0.975]
----------------------------------------------------------------------------------
const             -0.1161      0.080     -1.443      0.149      -0.274       0.042
size              -0.0029      0.008     -0.352      0.725      -0.019       0.013
equity_ratio      -0.2401      0.353     -0.681      0.496      -0.932       0.451
roa                7.5516      2.445      3.089      0.002       2.760      12.344
cash_ratio         0.6522      0.155      4.202      0.000       0.348       0.956
debt_ratio        -0.2889      0.373     -0.774      0.439      -1.020       0.442
asset_growth      -0.1285      0.094     -1.368      0.171      -0.312       0.056
market_to_book    -0.0597      0.030     -2.019      0.044      -0.118      -0.002
==============================================================================
Omnibus:                       21.939   Durbin-Watson:                   1.928
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               72.011
Skew:                           0.066   Prob(JB):                     2.31e-16
Kurtosis:                       5.274   Cond. No.                     1.97e+03
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)
[2] The condition number is large, 1.97e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

===== R4_march_2023_vw_adjusted =====
                              OLS Regression Results
=================================================================================
Dep. Variable:     vw_adj_cum_ret_202303   R-squared:                       0.225
Model:                               OLS   Adj. R-squared:                  0.208
Method:                    Least Squares   F-statistic:                     6.702
Date:                   Wed, 27 May 2026   Prob (F-statistic):           1.99e-07
Time:                           17:09:29   Log-Likelihood:                 346.24
No. Observations:                    333   AIC:                            -676.5
Df Residuals:                        325   BIC:                            -646.0
Df Model:                              7
Covariance Type:                     HC3
==================================================================================
                     coef    std err          z      P>|z|      [0.025      0.975]
----------------------------------------------------------------------------------
const              0.0849      0.039      2.179      0.029       0.009       0.161
size              -0.0190      0.004     -5.353      0.000      -0.026      -0.012
equity_ratio       0.3870      0.173      2.235      0.025       0.048       0.726
roa                0.6930      0.904      0.766      0.443      -1.079       2.465
cash_ratio         0.1651      0.075      2.211      0.027       0.019       0.311
debt_ratio         0.3470      0.104      3.321      0.001       0.142       0.552
asset_growth      -0.1221      0.051     -2.418      0.016      -0.221      -0.023
market_to_book    -0.0103      0.013     -0.763      0.446      -0.037       0.016
==============================================================================
Omnibus:                      150.903   Durbin-Watson:                   1.856
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1162.093
Skew:                          -1.702   Prob(JB):                    4.51e-253
Kurtosis:                      11.495   Cond. No.                     1.97e+03
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)
[2] The condition number is large, 1.97e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

===== R5_max_drawdown_main_period =====
                                OLS Regression Results
======================================================================================
Dep. Variable:     max_drawdown_202203_202303   R-squared:                       0.172
Model:                                    OLS   Adj. R-squared:                  0.154
Method:                         Least Squares   F-statistic:                     5.038
Date:                        Wed, 27 May 2026   Prob (F-statistic):           1.92e-05
Time:                                17:09:29   Log-Likelihood:                 257.46
No. Observations:                         336   AIC:                            -498.9
Df Residuals:                             328   BIC:                            -468.4
Df Model:                                   7
Covariance Type:                          HC3
==================================================================================
                     coef    std err          z      P>|z|      [0.025      0.975]
----------------------------------------------------------------------------------
const             -0.1892      0.047     -4.038      0.000      -0.281      -0.097
size              -0.0097      0.005     -2.045      0.041      -0.019      -0.000
equity_ratio       0.3353      0.223      1.503      0.133      -0.102       0.773
roa                1.6927      1.599      1.059      0.290      -1.441       4.826
cash_ratio         0.3039      0.086      3.535      0.000       0.135       0.472
debt_ratio        -0.0715      0.235     -0.303      0.762      -0.533       0.390
asset_growth      -0.1479      0.058     -2.531      0.011      -0.262      -0.033
market_to_book    -0.0461      0.018     -2.579      0.010      -0.081      -0.011
==============================================================================
Omnibus:                       92.259   Durbin-Watson:                   1.810
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              238.873
Skew:                          -1.299   Prob(JB):                     1.35e-52
Kurtosis:                       6.211   Cond. No.                     1.96e+03
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)
[2] The condition number is large, 1.96e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

Robustness table, wide format:

model            R1_raw_return_main_period R2_ew_bank_adjusted_main_period R3_extended_vw_adjusted_202203_202307 R4_march_2023_vw_adjusted R5_max_drawdown_main_period
asset_growth                     -0.1721**                       -0.1861**                               -0.1285                 -0.1221**                   -0.1479**
asset_growth_t                     (-2.29)                         (-2.10)                               (-1.37)                   (-2.42)                     (-2.53)
cash_ratio                       0.6426***                       0.7573***                             0.6522***                  0.1651**                   0.3039***
cash_ratio_t                        (5.03)                          (5.00)                                (4.20)                    (2.21)                      (3.53)
const                              -0.0220                        0.1543**                               -0.1161                  0.0849**                  -0.1892***
const_t                            (-0.35)                          (2.09)                               (-1.44)                    (2.18)                     (-4.04)
debt_ratio                         -0.1678                         -0.2638                               -0.2889                 0.3470***                     -0.0715
debt_ratio_t                       (-0.72)                         (-0.97)                               (-0.77)                    (3.32)                     (-0.30)
equity_ratio                        0.3384                          0.3586                               -0.2401                  0.3870**                      0.3353
equity_ratio_t                      (1.13)                          (1.00)                               (-0.68)                    (2.23)                      (1.50)
market_to_book                   -0.0511**                       -0.0629**                             -0.0597**                   -0.0103                  -0.0461***
market_to_book_t                   (-2.11)                         (-2.16)                               (-2.02)                   (-0.76)                     (-2.58)
roa                                 2.2172                          3.2091                             7.5516***                    0.6930                      1.6927
roa_t                               (1.29)                          (1.59)                                (3.09)                    (0.77)                      (1.06)
size                            -0.0242***                      -0.0200***                               -0.0029                -0.0190***                   -0.0097**
size_t                             (-4.03)                         (-2.81)                               (-0.35)                   (-5.35)                     (-2.04)
N                                      336                             336                                   333                       333                         336
R2                                  0.1780                          0.1565                                0.1216                    0.2250                      0.1721
Adj_R2                              0.1605                          0.1385                                0.1027                    0.2083                      0.1545

                                   model                             y    N      R2  Adj_R2  F_pvalue
0              R1_raw_return_main_period     raw_cum_ret_202203_202303  336 0.17805 0.16051   0.00000
1        R2_ew_bank_adjusted_main_period  ew_adj_cum_ret_202203_202303  336 0.15652 0.13852   0.00000
2  R3_extended_vw_adjusted_202203_202307  vw_adj_cum_ret_202203_202307  333 0.12158 0.10266   0.00000
3              R4_march_2023_vw_adjusted         vw_adj_cum_ret_202303  333 0.22495 0.20826   0.00000
4            R5_max_drawdown_main_period    max_drawdown_202203_202303  336 0.17213 0.15446   0.00002

In [51]:
# =========================================================
# Cell 22. Commercial bank only robustness: SIC 6020 only
# =========================================================

if "sich_num" in reg_df.columns:
    reg_commercial = reg_df[reg_df["sich_num"].eq(6020)].copy()
else:
    reg_commercial = pd.DataFrame()

reg_commercial_main = reg_commercial.dropna(subset=[main_y] + x_vars_main).copy()

print("Commercial bank only sample:", reg_commercial_main.shape)

commercial_models = {}
commercial_tables = pd.DataFrame()
commercial_fit = pd.DataFrame()
commercial_table_wide = pd.DataFrame()

if len(reg_commercial_main) >= 30:
    c_ols1, c_table1, c_fit1 = run_ols(
        reg_commercial_main,
        main_y,
        x_model1,
        "C1_commercial_basic"
    )

    c_ols2, c_table2, c_fit2 = run_ols(
        reg_commercial_main,
        main_y,
        x_model2,
        "C2_commercial_balance_sheet"
    )

    c_ols3, c_table3, c_fit3 = run_ols(
        reg_commercial_main,
        main_y,
        x_model3,
        "C3_commercial_full"
    )

    commercial_models = {
        "C1_commercial_basic": c_ols1,
        "C2_commercial_balance_sheet": c_ols2,
        "C3_commercial_full": c_ols3
    }

    commercial_tables = pd.concat([c_table1, c_table2, c_table3], ignore_index=True)
    commercial_fit = pd.DataFrame([c_fit1, c_fit2, c_fit3])
    commercial_table_wide = make_regression_wide_table(commercial_tables, commercial_fit)

    print("\nCommercial bank only regression table:")
    display(commercial_table_wide)
    display(commercial_fit)

else:
    print("Commercial bank only regression skipped because sample is too small.")

Commercial bank only sample: (279, 34)

Commercial bank only regression table:

model            C1_commercial_basic C2_commercial_balance_sheet C3_commercial_full
asset_growth                     NaN                    -0.2018*            -0.1202
asset_growth_t                   NaN                     (-1.78)            (-1.20)
cash_ratio                       NaN                   0.6797***          0.7219***
cash_ratio_t                     NaN                      (3.68)             (4.13)
const                         0.0634                      0.0453             0.0835
const_t                       (0.65)                      (0.43)             (0.79)
debt_ratio                       NaN                     -0.5207            -0.5446
debt_ratio_t                     NaN                     (-1.19)            (-1.27)
equity_ratio                1.4880**                   1.8364***            1.2468*
equity_ratio_t                (2.06)                      (2.62)             (1.77)
market_to_book                   NaN                         NaN         -0.0956***
market_to_book_t                 NaN                         NaN            (-3.30)
roa                          -0.4718                     -1.6657             4.7410
roa_t                        (-0.12)                     (-0.46)             (1.20)
size                      -0.0301***                  -0.0328***         -0.0263***
size_t                       (-3.26)                     (-3.68)            (-3.12)
N                                279                         279                279
R2                            0.0649                      0.1467             0.1839
Adj_R2                        0.0547                      0.1278             0.1628

                         model                             y    N      R2  Adj_R2  F_pvalue
0          C1_commercial_basic  vw_adj_cum_ret_202203_202303  279 0.06488 0.05468   0.00827
1  C2_commercial_balance_sheet  vw_adj_cum_ret_202203_202303  279 0.14667 0.12784   0.00000
2           C3_commercial_full  vw_adj_cum_ret_202203_202303  279 0.18390 0.16282   0.00000

In [52]:
# =========================================================
# Cell 23. Summary statistics and correlation table
# =========================================================

summary_vars = [main_y] + x_vars_main

summary_stats = reg_main[summary_vars].describe().T
summary_stats["missing_count"] = reg_main[summary_vars].isna().sum()
summary_stats["missing_ratio"] = reg_main[summary_vars].isna().mean()

corr_matrix = reg_main[summary_vars].corr()

print("Summary Statistics")
display(summary_stats)

print("Correlation Matrix")
display(corr_matrix)

Summary Statistics

                                 count     mean     std      min      25%      50%     75%      max  missing_count  missing_ratio
vw_adj_cum_ret_202203_202303 336.00000 -0.05043 0.20415 -0.75413 -0.18053 -0.04839 0.07535  0.40138              0        0.00000
size                         336.00000  8.91627 1.66781  6.24381  7.69725  8.63320 9.73148 14.37665              0        0.00000
equity_ratio                 336.00000  0.10723 0.03941  0.05870  0.08827  0.10105 0.11702  0.42227              0        0.00000
roa                          336.00000  0.01264 0.00784 -0.00075  0.00937  0.01159 0.01413  0.06581              0        0.00000
cash_ratio                   336.00000  0.10954 0.07982  0.00895  0.04692  0.09014 0.14841  0.35697              0        0.00000
debt_ratio                   336.00000  0.05173 0.05347  0.00050  0.02198  0.03596 0.06127  0.34349              0        0.00000
asset_growth                 336.00000  0.15026 0.19514 -0.06924  0.04761  0.09871 0.17606  1.18327              0        0.00000
market_to_book               336.00000  1.38901 0.65511  0.68879  1.05071  1.21058 1.45542  4.82887              0        0.00000

Correlation Matrix

                              vw_adj_cum_ret_202203_202303     size  equity_ratio      roa  cash_ratio  debt_ratio  asset_growth  market_to_book
vw_adj_cum_ret_202203_202303                       1.00000 -0.12309       0.12327  0.10357     0.20304    -0.06176      -0.13692        -0.14559
size                                              -0.12309  1.00000      -0.01509  0.16604     0.12573     0.28974      -0.05044         0.22622
equity_ratio                                       0.12327 -0.01509       1.00000  0.70686     0.00683     0.14765      -0.02343         0.18091
roa                                                0.10357  0.16604       0.70686  1.00000     0.05156     0.22523      -0.16153         0.41178
cash_ratio                                         0.20304  0.12573       0.00683  0.05156     1.00000    -0.01698       0.23500         0.14670
debt_ratio                                        -0.06176  0.28974       0.14765  0.22523    -0.01698     1.00000      -0.12227         0.11494
asset_growth                                      -0.13692 -0.05044      -0.02343 -0.16153     0.23500    -0.12227       1.00000         0.14728
market_to_book                                    -0.14559  0.22622       0.18091  0.41178     0.14670     0.11494       0.14728         1.00000

In [53]:
# =========================================================
# Cell 24. 주요 결과 저장
# =========================================================

saved_files = []

def save_df(df, filename, index=False):
    if df is not None and isinstance(df, pd.DataFrame):
        path = os.path.join(output_folder, filename)
        df.to_csv(path, index=index, encoding="utf-8-sig")
        saved_files.append(path)
        print(f"Saved: {filename}")

def save_txt(text, filename):
    path = os.path.join(output_folder, filename)
    with open(path, "w", encoding="utf-8") as f:
        f.write(text)
    saved_files.append(path)
    print(f"Saved: {filename}")

# Data and diagnostics
# CRSP-FRB Link 관련 저장
save_df(bank_permco_link_all, "00_crsp_frb_link_all_raw.csv")
save_df(bank_permco_link_filtered, "00_crsp_frb_link_active_2021_2023.csv")
save_df(bank_permco_list_raw, "01_crsp_frb_active_one_row_per_permco.csv")
save_df(bank_permco_list_raw, "01_professor_bank_permco_list_raw.csv")
save_df(sample_diagnostics, "02_sample_diagnostics.csv")
save_df(permno_count_by_permco, "03_permno_count_by_permco.csv")
save_df(bank_bench, "04_monthly_bank_benchmark_returns.csv")
save_df(y_main, "05_y_main_202203_202303.csv")
save_df(y_extended, "06_y_extended_202203_202307.csv")
save_df(y_march, "07_y_march_202303.csv")
save_df(permco_x, "08_permco_compustat_accounting_variables_2021.csv")
save_df(analysis_df, "09_analysis_data_permco_level.csv")
save_df(reg_df, "10_regression_data_all.csv")
save_df(reg_main, "11_final_main_regression_sample.csv")

# Tables
save_df(summary_stats, "12_summary_statistics.csv", index=True)
save_df(corr_matrix, "13_correlation_matrix.csv", index=True)
save_df(ols_tables, "14_main_ols_results_long.csv")
save_df(ols_fit, "15_main_ols_fit.csv")
save_df(main_regression_table_wide, "16_main_regression_table_wide.csv", index=True)
save_df(robust_ols_tables, "17_robustness_ols_results_long.csv")
save_df(robust_ols_fit, "18_robustness_ols_fit.csv")
save_df(robustness_table_wide, "19_robustness_table_wide.csv", index=True)
save_df(commercial_tables, "20_commercial_bank_only_results_long.csv")
save_df(commercial_fit, "21_commercial_bank_only_fit.csv")
save_df(commercial_table_wide, "22_commercial_bank_only_table_wide.csv", index=True)

# Full model summaries
save_txt(ols1.summary().as_text(), "23_ols1_basic_full_summary.txt")
save_txt(ols2.summary().as_text(), "24_ols2_balance_sheet_full_summary.txt")
save_txt(ols3.summary().as_text(), "25_ols3_full_model_summary.txt")

for name, model in robust_models.items():
    safe_name = re.sub(r"[^A-Za-z0-9_]+", "_", name)
    save_txt(model.summary().as_text(), f"26_{safe_name}_summary.txt")

# ZIP
zip_path = os.path.join(output_folder, "permco_bank_analysis_results.zip")

with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
    for file in saved_files:
        if os.path.exists(file):
            zf.write(file, arcname=os.path.basename(file))

print("\nZIP saved:", zip_path)
print("Number of saved files:", len(saved_files))

Saved: 00_crsp_frb_link_all_raw.csv
Saved: 00_crsp_frb_link_active_2021_2023.csv
Saved: 01_crsp_frb_active_one_row_per_permco.csv
Saved: 01_professor_bank_permco_list_raw.csv
Saved: 02_sample_diagnostics.csv
Saved: 03_permno_count_by_permco.csv
Saved: 04_monthly_bank_benchmark_returns.csv
Saved: 05_y_main_202203_202303.csv
Saved: 06_y_extended_202203_202307.csv
Saved: 07_y_march_202303.csv
Saved: 08_permco_compustat_accounting_variables_2021.csv
Saved: 09_analysis_data_permco_level.csv
Saved: 10_regression_data_all.csv
Saved: 11_final_main_regression_sample.csv
Saved: 12_summary_statistics.csv
Saved: 13_correlation_matrix.csv
Saved: 14_main_ols_results_long.csv
Saved: 15_main_ols_fit.csv
Saved: 16_main_regression_table_wide.csv
Saved: 17_robustness_ols_results_long.csv
Saved: 18_robustness_ols_fit.csv
Saved: 19_robustness_table_wide.csv
Saved: 20_commercial_bank_only_results_long.csv
Saved: 21_commercial_bank_only_fit.csv
Saved: 22_commercial_bank_only_table_wide.csv
Saved: 23_ols1_basic_full_summary.txt
Saved: 24_ols2_balance_sheet_full_summary.txt
Saved: 25_ols3_full_model_summary.txt
Saved: 26_R1_raw_return_main_period_summary.txt
Saved: 26_R2_ew_bank_adjusted_main_period_summary.txt
Saved: 26_R3_extended_vw_adjusted_202203_202307_summary.txt
Saved: 26_R4_march_2023_vw_adjusted_summary.txt
Saved: 26_R5_max_drawdown_main_period_summary.txt

ZIP saved: C:\Users\starw\OneDrive\바탕 화면\학교 생활\UNIST\Research\박지훈 자료\permco_bank_analysis_output\permco_bank_analysis_results.zip
Number of saved files: 33

In [54]:
# =========================================================
# Cell 25. 결과 빠른 해석 자동 생성
# =========================================================

def get_coef_info(table, model_name, variable):
    temp = table[(table["model"] == model_name) & (table["variable"] == variable)].copy()
    if len(temp) == 0:
        return None
    row = temp.iloc[0]
    return {
        "coef": row["coef"],
        "t": row["t_stat"],
        "p": row["p_value"],
        "stars": row["stars"]
    }

key_vars = ["cash_ratio", "asset_growth", "debt_ratio", "market_to_book", "equity_ratio", "roa", "size"]

interpret_rows = []

for var in key_vars:
    info = get_coef_info(ols_tables, "M3_full", var)
    if info is not None:
        interpret_rows.append({
            "variable": var,
            "coef": info["coef"],
            "t_stat": info["t"],
            "p_value": info["p"],
            "stars": info["stars"],
            "direction": "positive" if info["coef"] > 0 else "negative"
        })

key_result_summary = pd.DataFrame(interpret_rows)

print("Key results from M3_full:")
display(key_result_summary)

# 간단한 문장 생성
for _, row in key_result_summary.iterrows():
    var = row["variable"]
    direction = row["direction"]
    stars = row["stars"]
    sig_text = "statistically significant" if stars != "" else "not statistically significant"
    print(f"{var}: {direction}, {sig_text}, coef={row['coef']:.4f}, t={row['t_stat']:.2f}, p={row['p_value']:.4f}")

Key results from M3_full:

         variable     coef   t_stat  p_value stars direction
0      cash_ratio  0.71081  4.87448  0.00000   ***  positive
1    asset_growth -0.17312 -2.05163  0.04021    **  negative
2      debt_ratio -0.21886 -0.85910  0.39029        negative
3  market_to_book -0.05961 -2.13771  0.03254    **  negative
4    equity_ratio  0.36066  1.05929  0.28947        positive
5             roa  3.28135  1.72792  0.08400     *  positive
6            size -0.01547 -2.29299  0.02185    **  negative

cash_ratio: positive, statistically significant, coef=0.7108, t=4.87, p=0.0000
asset_growth: negative, statistically significant, coef=-0.1731, t=-2.05, p=0.0402
debt_ratio: negative, not statistically significant, coef=-0.2189, t=-0.86, p=0.3903
market_to_book: negative, statistically significant, coef=-0.0596, t=-2.14, p=0.0325
equity_ratio: positive, not statistically significant, coef=0.3607, t=1.06, p=0.2895
roa: positive, statistically significant, coef=3.2814, t=1.73, p=0.0840
size: negative, statistically significant, coef=-0.0155, t=-2.29, p=0.0218

In [55]:
# =========================================================
# Cell 26. 교수님 미팅용 1페이지 요약 자동 생성
# =========================================================

def coef_sentence(var, label):
    info = get_coef_info(ols_tables, "M3_full", var)
    if info is None:
        return f"- {label}: not available in the full model."
    direction = "positive" if info["coef"] > 0 else "negative"
    sig = "statistically significant" if info["stars"] != "" else "not statistically significant"
    return f"- {label}: {direction} coefficient ({info['coef']:.4f}), t = {info['t']:.2f}, p = {info['p']:.4f}; {sig}."

meeting_summary = f"""
PERMCO-Based Bank Analysis Summary
==================================

1. Purpose
----------
Following the professor's instruction, I reconstructed the bank sample using the professor-provided CRSP PERMCO bank list. I then repeated the same analysis using PERMCO-level bank stock returns and 2021 pre-shock Compustat accounting variables.

2. Sample Construction
----------------------
- Professor-provided bank PERMCO list: {len(bank_permcos):,} unique PERMCOs.
- CRSP bank PERMCOs with monthly return data during the shock window: {permco_monthly['PERMCO'].nunique():,}.
- PERMCOs with main-period return outcome from March 2022 to March 2023: {y_main['PERMCO'].nunique():,}.
- PERMCOs matched to Compustat 2021 accounting variables: {permco_x['PERMCO'].nunique():,}.
- Final main regression sample: {reg_main['PERMCO'].nunique():,} PERMCOs.

3. Main Outcome Variable
------------------------
The main dependent variable is the value-weighted bank-benchmark-adjusted cumulative return from March 2022 to March 2023. Returns are adjusted for delisting returns when available. The bank benchmark is constructed using PERMCO-level bank returns.

4. Main Regression
------------------
The full model includes:
Size, EquityRatio, ROA, CashRatio, DebtRatio, AssetGrowth, and MarketToBook.

5. Key Full-Model Results
-------------------------
{coef_sentence("cash_ratio", "CashRatio")}
{coef_sentence("asset_growth", "AssetGrowth")}
{coef_sentence("debt_ratio", "DebtRatio")}
{coef_sentence("market_to_book", "MarketToBook")}
{coef_sentence("equity_ratio", "EquityRatio")}

6. Interpretation
-----------------
The main question is whether pre-shock bank balance sheet characteristics explain cross-sectional differences in bank stock performance during the 2022-2023 interest rate shock. The PERMCO-based analysis directly follows the professor's instruction by identifying banks at the CRSP company level rather than relying only on SIC/CUSIP-based sample construction.

7. Tables Prepared
------------------
- Sample diagnostics table
- Summary statistics
- Correlation matrix
- Main regression table
- Robustness regression table
- Commercial-bank-only robustness table, if sample size permits

8. Files Saved
--------------
All tables and regression outputs are saved in:
{output_folder}
"""

print(meeting_summary)

save_txt(meeting_summary, "27_meeting_summary_permco_analysis.txt")

PERMCO-Based Bank Analysis Summary
==================================

1. Purpose
----------
Following the professor's instruction, I reconstructed the bank sample using the professor-provided CRSP PERMCO bank list. I then repeated the same analysis using PERMCO-level bank stock returns and 2021 pre-shock Compustat accounting variables.

2. Sample Construction
----------------------
- Professor-provided bank PERMCO list: 394 unique PERMCOs.
- CRSP bank PERMCOs with monthly return data during the shock window: 362.
- PERMCOs with main-period return outcome from March 2022 to March 2023: 345.
- PERMCOs matched to Compustat 2021 accounting variables: 354.
- Final main regression sample: 336 PERMCOs.

3. Main Outcome Variable
------------------------
The main dependent variable is the value-weighted bank-benchmark-adjusted cumulative return from March 2022 to March 2023. Returns are adjusted for delisting returns when available. The bank benchmark is constructed using PERMCO-level bank returns.

4. Main Regression
------------------
The full model includes:
Size, EquityRatio, ROA, CashRatio, DebtRatio, AssetGrowth, and MarketToBook.

5. Key Full-Model Results
-------------------------
- CashRatio: positive coefficient (0.7108), t = 4.87, p = 0.0000; statistically significant.
- AssetGrowth: negative coefficient (-0.1731), t = -2.05, p = 0.0402; statistically significant.
- DebtRatio: negative coefficient (-0.2189), t = -0.86, p = 0.3903; not statistically significant.
- MarketToBook: negative coefficient (-0.0596), t = -2.14, p = 0.0325; statistically significant.
- EquityRatio: positive coefficient (0.3607), t = 1.06, p = 0.2895; not statistically significant.

6. Interpretation
-----------------
The main question is whether pre-shock bank balance sheet characteristics explain cross-sectional differences in bank stock performance during the 2022-2023 interest rate shock. The PERMCO-based analysis directly follows the professor's instruction by identifying banks at the CRSP company level rather than relying only on SIC/CUSIP-based sample construction.

7. Tables Prepared
------------------
- Sample diagnostics table
- Summary statistics
- Correlation matrix
- Main regression table
- Robustness regression table
- Commercial-bank-only robustness table, if sample size permits

8. Files Saved
--------------
All tables and regression outputs are saved in:
C:\Users\starw\OneDrive\바탕 화면\학교 생활\UNIST\Research\박지훈 자료\permco_bank_analysis_output

Saved: 27_meeting_summary_permco_analysis.txt

In [56]:
# =========================================================
# Cell 27. ChatGPT에게 결과 보여줄 때 복붙용
# =========================================================

def df_to_markdown_safe(df, max_rows=30):
    if df is None or len(df) == 0:
        return "EMPTY"
    try:
        return df.head(max_rows).to_markdown()
    except:
        return df.head(max_rows).to_string()

gpt_report = f"""
I reran the bank fragility analysis using the professor-provided PERMCO bank list.

========================
1. SAMPLE DIAGNOSTICS
========================

{df_to_markdown_safe(sample_diagnostics, 20)}

========================
2. FINAL REGRESSION SAMPLE
========================

reg_df shape: {reg_df.shape}
reg_main shape: {reg_main.shape}
Unique PERMCO in reg_main: {reg_main['PERMCO'].nunique()}
Unique gvkey in reg_main: {reg_main['gvkey'].nunique()}

========================
3. SIC DISTRIBUTION
========================

{df_to_markdown_safe(reg_main['sich_num'].value_counts(dropna=False).sort_index().reset_index().rename(columns={'index':'sich_num', 'sich_num':'N'}), 50)}

========================
4. SUMMARY STATISTICS
========================

{df_to_markdown_safe(summary_stats, 50)}

========================
5. CORRELATION MATRIX
========================

{df_to_markdown_safe(corr_matrix, 50)}

========================
6. MAIN REGRESSION TABLE
========================

{df_to_markdown_safe(main_regression_table_wide, 80)}

========================
7. MAIN MODEL FIT
========================

{df_to_markdown_safe(ols_fit, 20)}

========================
8. ROBUSTNESS TABLE
========================

{df_to_markdown_safe(robustness_table_wide, 100)}

========================
9. ROBUSTNESS MODEL FIT
========================

{df_to_markdown_safe(robust_ols_fit, 50)}

========================
10. COMMERCIAL BANK ONLY TABLE
========================

{df_to_markdown_safe(commercial_table_wide, 80)}

========================
11. COMMERCIAL BANK ONLY MODEL FIT
========================

{df_to_markdown_safe(commercial_fit, 20)}

========================
12. KEY FULL MODEL COEFFICIENTS
========================

{df_to_markdown_safe(key_result_summary, 30)}

========================
13. TASK FOR CHATGPT
========================

Please interpret these PERMCO-based results for my meeting with the professor.
Focus on:
1. whether the PERMCO-based sample construction worked,
2. whether the main liquidity / asset growth / market-to-book results are consistent with the earlier analysis,
3. whether the results are strong enough to discuss with the professor,
4. what tables I should bring to the meeting,
5. what weaknesses or caveats I should mention,
6. what next empirical step I should take.
"""

print(gpt_report)

# 저장도 해둠
gpt_report_path = os.path.join(output_folder, "28_COPY_THIS_TO_CHATGPT.txt")
with open(gpt_report_path, "w", encoding="utf-8") as f:
    f.write(gpt_report)

print("\nSaved copy-paste report to:")
print(gpt_report_path)

I reran the bank fragility analysis using the professor-provided PERMCO bank list.

========================
1. SAMPLE DIAGNOSTICS
========================

|    | step                                              |   N_PERMCO |   N_rows |
|---:|:--------------------------------------------------|-----------:|---------:|
|  0 | Raw CRSP-FRB Link file                            |       1450 |     1495 |
|  1 | CRSP-FRB links active during 2021-2023            |        394 |      395 |
|  2 | One row per active PERMCO bank list               |        394 |      394 |
|  3 | CRSP bank PERMCOs with monthly return data        |        362 |     5898 |
|  4 | PERMCOs with main-period Y variable               |        345 |      345 |
|  5 | PERMCOs matched to Compustat 2021 accounting data |        354 |      354 |
|  6 | Final main regression sample                      |        336 |      336 |

========================
2. FINAL REGRESSION SAMPLE
========================

reg_df shape: (345, 34)
reg_main shape: (336, 34)
Unique PERMCO in reg_main: 336
Unique gvkey in reg_main: 336

========================
3. SIC DISTRIBUTION
========================

|    |    N |   count |
|---:|-----:|--------:|
|  0 | 6020 |     279 |
|  1 | 6035 |      21 |
|  2 | 6036 |      14 |
|  3 | 6141 |       5 |
|  4 | 6162 |       1 |
|  5 | 6172 |       1 |
|  6 | 6199 |       2 |
|  7 | 6211 |       4 |
|  8 | 6282 |       5 |
|  9 | 6311 |       1 |
| 10 | 6331 |       1 |
| 11 | 6361 |       1 |
| 12 | 7389 |       1 |

========================
4. SUMMARY STATISTICS
========================

|                              |   count |       mean |        std |          min |         25% |        50% |       75% |       max |   missing_count |   missing_ratio |
|:-----------------------------|--------:|-----------:|-----------:|-------------:|------------:|-----------:|----------:|----------:|----------------:|----------------:|
| vw_adj_cum_ret_202203_202303 |     336 | -0.0504317 | 0.20415    | -0.754133    | -0.18053    | -0.0483875 | 0.0753542 |  0.40138  |               0 |               0 |
| size                         |     336 |  8.91627   | 1.66781    |  6.24381     |  7.69725    |  8.6332    | 9.73148   | 14.3766   |               0 |               0 |
| equity_ratio                 |     336 |  0.107233  | 0.039412   |  0.0587004   |  0.088267   |  0.101052  | 0.117023  |  0.422267 |               0 |               0 |
| roa                          |     336 |  0.0126372 | 0.00783635 | -0.000753842 |  0.00936834 |  0.011594  | 0.0141283 |  0.065813 |               0 |               0 |
| cash_ratio                   |     336 |  0.109538  | 0.0798231  |  0.00895139  |  0.0469177  |  0.0901359 | 0.14841   |  0.356968 |               0 |               0 |
| debt_ratio                   |     336 |  0.0517268 | 0.0534736  |  0.000497992 |  0.0219841  |  0.0359563 | 0.0612749 |  0.343491 |               0 |               0 |
| asset_growth                 |     336 |  0.150257  | 0.195136   | -0.0692352   |  0.0476145  |  0.0987096 | 0.176056  |  1.18327  |               0 |               0 |
| market_to_book               |     336 |  1.38901   | 0.655108   |  0.688789    |  1.05071    |  1.21058   | 1.45542   |  4.82887  |               0 |               0 |

========================
5. CORRELATION MATRIX
========================

|                              |   vw_adj_cum_ret_202203_202303 |       size |   equity_ratio |        roa |   cash_ratio |   debt_ratio |   asset_growth |   market_to_book |
|:-----------------------------|-------------------------------:|-----------:|---------------:|-----------:|-------------:|-------------:|---------------:|-----------------:|
| vw_adj_cum_ret_202203_202303 |                      1         | -0.123094  |     0.123274   |  0.103572  |   0.203038   |   -0.0617622 |     -0.136923  |        -0.145589 |
| size                         |                     -0.123094  |  1         |    -0.0150913  |  0.166037  |   0.12573    |    0.289742  |     -0.0504444 |         0.226217 |
| equity_ratio                 |                      0.123274  | -0.0150913 |     1          |  0.706863  |   0.00683042 |    0.147651  |     -0.0234281 |         0.180909 |
| roa                          |                      0.103572  |  0.166037  |     0.706863   |  1         |   0.0515557  |    0.225226  |     -0.161527  |         0.41178  |
| cash_ratio                   |                      0.203038  |  0.12573   |     0.00683042 |  0.0515557 |   1          |   -0.0169776 |      0.234997  |         0.146705 |
| debt_ratio                   |                     -0.0617622 |  0.289742  |     0.147651   |  0.225226  |  -0.0169776  |    1         |     -0.122274  |         0.11494  |
| asset_growth                 |                     -0.136923  | -0.0504444 |    -0.0234281  | -0.161527  |   0.234997   |   -0.122274  |      1         |         0.147278 |
| market_to_book               |                     -0.145589  |  0.226217  |     0.180909   |  0.41178   |   0.146705   |    0.11494   |      0.147278  |         1        |

========================
6. MAIN REGRESSION TABLE
========================

|                  | M1_basic   | M2_balance_sheet   | M3_full   |
|:-----------------|:-----------|:-------------------|:----------|
| asset_growth     | nan        | -0.2197**          | -0.1731** |
| asset_growth_t   | nan        | (-2.41)            | (-2.05)   |
| cash_ratio       | nan        | 0.6876***          | 0.7108*** |
| cash_ratio_t     | nan        | (4.52)             | (4.87)    |
| const            | 0.0353     | 0.0164             | 0.0496    |
| const_t          | (0.50)     | (0.23)             | (0.70)    |
| debt_ratio       | nan        | -0.2252            | -0.2189   |
| debt_ratio_t     | nan        | (-0.81)            | (-0.86)   |
| equity_ratio     | 0.3324     | 0.5837             | 0.3607    |
| equity_ratio_t   | (0.83)     | (1.54)             | (1.06)    |
| market_to_book   | nan        | nan                | -0.0596** |
| market_to_book_t | nan        | nan                | (-2.14)   |
| roa              | 2.1026     | 0.3783             | 3.2814*   |
| roa_t            | (1.11)     | (0.22)             | (1.73)    |
| size             | -0.0166**  | -0.0185***         | -0.0155** |
| size_t           | (-2.25)    | (-2.59)            | (-2.29)   |
| N                | 336        | 336                | 336       |
| R2               | 0.0330     | 0.1210             | 0.1477    |
| Adj_R2           | 0.0242     | 0.1049             | 0.1295    |

========================
7. MAIN MODEL FIT
========================

|    | model            | y                            |   N |        R2 |    Adj_R2 |    F_pvalue |
|---:|:-----------------|:-----------------------------|----:|----------:|----------:|------------:|
|  0 | M1_basic         | vw_adj_cum_ret_202203_202303 | 336 | 0.0329531 | 0.0242148 | 0.00588506  |
|  1 | M2_balance_sheet | vw_adj_cum_ret_202203_202303 | 336 | 0.120974  | 0.104943  | 2.27152e-06 |
|  2 | M3_full          | vw_adj_cum_ret_202203_202303 | 336 | 0.147659  | 0.129469  | 8.14951e-08 |

========================
8. ROBUSTNESS TABLE
========================

|                  | R1_raw_return_main_period   | R2_ew_bank_adjusted_main_period   | R3_extended_vw_adjusted_202203_202307   | R4_march_2023_vw_adjusted   | R5_max_drawdown_main_period   |
|:-----------------|:----------------------------|:----------------------------------|:----------------------------------------|:----------------------------|:------------------------------|
| asset_growth     | -0.1721**                   | -0.1861**                         | -0.1285                                 | -0.1221**                   | -0.1479**                     |
| asset_growth_t   | (-2.29)                     | (-2.10)                           | (-1.37)                                 | (-2.42)                     | (-2.53)                       |
| cash_ratio       | 0.6426***                   | 0.7573***                         | 0.6522***                               | 0.1651**                    | 0.3039***                     |
| cash_ratio_t     | (5.03)                      | (5.00)                            | (4.20)                                  | (2.21)                      | (3.53)                        |
| const            | -0.0220                     | 0.1543**                          | -0.1161                                 | 0.0849**                    | -0.1892***                    |
| const_t          | (-0.35)                     | (2.09)                            | (-1.44)                                 | (2.18)                      | (-4.04)                       |
| debt_ratio       | -0.1678                     | -0.2638                           | -0.2889                                 | 0.3470***                   | -0.0715                       |
| debt_ratio_t     | (-0.72)                     | (-0.97)                           | (-0.77)                                 | (3.32)                      | (-0.30)                       |
| equity_ratio     | 0.3384                      | 0.3586                            | -0.2401                                 | 0.3870**                    | 0.3353                        |
| equity_ratio_t   | (1.13)                      | (1.00)                            | (-0.68)                                 | (2.23)                      | (1.50)                        |
| market_to_book   | -0.0511**                   | -0.0629**                         | -0.0597**                               | -0.0103                     | -0.0461***                    |
| market_to_book_t | (-2.11)                     | (-2.16)                           | (-2.02)                                 | (-0.76)                     | (-2.58)                       |
| roa              | 2.2172                      | 3.2091                            | 7.5516***                               | 0.6930                      | 1.6927                        |
| roa_t            | (1.29)                      | (1.59)                            | (3.09)                                  | (0.77)                      | (1.06)                        |
| size             | -0.0242***                  | -0.0200***                        | -0.0029                                 | -0.0190***                  | -0.0097**                     |
| size_t           | (-4.03)                     | (-2.81)                           | (-0.35)                                 | (-5.35)                     | (-2.04)                       |
| N                | 336                         | 336                               | 333                                     | 333                         | 336                           |
| R2               | 0.1780                      | 0.1565                            | 0.1216                                  | 0.2250                      | 0.1721                        |
| Adj_R2           | 0.1605                      | 0.1385                            | 0.1027                                  | 0.2083                      | 0.1545                        |

========================
9. ROBUSTNESS MODEL FIT
========================

|    | model                                 | y                            |   N |       R2 |   Adj_R2 |    F_pvalue |
|---:|:--------------------------------------|:-----------------------------|----:|---------:|---------:|------------:|
|  0 | R1_raw_return_main_period             | raw_cum_ret_202203_202303    | 336 | 0.178049 | 0.160507 | 2.20029e-09 |
|  1 | R2_ew_bank_adjusted_main_period       | ew_adj_cum_ret_202203_202303 | 336 | 0.156518 | 0.138517 | 4.08689e-08 |
|  2 | R3_extended_vw_adjusted_202203_202307 | vw_adj_cum_ret_202203_202307 | 333 | 0.12158  | 0.10266  | 4.6032e-06  |
|  3 | R4_march_2023_vw_adjusted             | vw_adj_cum_ret_202303        | 333 | 0.224953 | 0.20826  | 1.99218e-07 |
|  4 | R5_max_drawdown_main_period           | max_drawdown_202203_202303   | 336 | 0.172131 | 0.154463 | 1.922e-05   |

========================
10. COMMERCIAL BANK ONLY TABLE
========================

|                  | C1_commercial_basic   | C2_commercial_balance_sheet   | C3_commercial_full   |
|:-----------------|:----------------------|:------------------------------|:---------------------|
| asset_growth     | nan                   | -0.2018*                      | -0.1202              |
| asset_growth_t   | nan                   | (-1.78)                       | (-1.20)              |
| cash_ratio       | nan                   | 0.6797***                     | 0.7219***            |
| cash_ratio_t     | nan                   | (3.68)                        | (4.13)               |
| const            | 0.0634                | 0.0453                        | 0.0835               |
| const_t          | (0.65)                | (0.43)                        | (0.79)               |
| debt_ratio       | nan                   | -0.5207                       | -0.5446              |
| debt_ratio_t     | nan                   | (-1.19)                       | (-1.27)              |
| equity_ratio     | 1.4880**              | 1.8364***                     | 1.2468*              |
| equity_ratio_t   | (2.06)                | (2.62)                        | (1.77)               |
| market_to_book   | nan                   | nan                           | -0.0956***           |
| market_to_book_t | nan                   | nan                           | (-3.30)              |
| roa              | -0.4718               | -1.6657                       | 4.7410               |
| roa_t            | (-0.12)               | (-0.46)                       | (1.20)               |
| size             | -0.0301***            | -0.0328***                    | -0.0263***           |
| size_t           | (-3.26)               | (-3.68)                       | (-3.12)              |
| N                | 279                   | 279                           | 279                  |
| R2               | 0.0649                | 0.1467                        | 0.1839               |
| Adj_R2           | 0.0547                | 0.1278                        | 0.1628               |

========================
11. COMMERCIAL BANK ONLY MODEL FIT
========================

|    | model                       | y                            |   N |        R2 |    Adj_R2 |    F_pvalue |
|---:|:----------------------------|:-----------------------------|----:|----------:|----------:|------------:|
|  0 | C1_commercial_basic         | vw_adj_cum_ret_202203_202303 | 279 | 0.0648818 | 0.0546805 | 0.0082713   |
|  1 | C2_commercial_balance_sheet | vw_adj_cum_ret_202203_202303 | 279 | 0.146667  | 0.127844  | 3.89172e-06 |
|  2 | C3_commercial_full          | vw_adj_cum_ret_202203_202303 | 279 | 0.183899  | 0.162819  | 3.70957e-08 |

========================
12. KEY FULL MODEL COEFFICIENTS
========================

|    | variable       |       coef |    t_stat |     p_value | stars   | direction   |
|---:|:---------------|-----------:|----------:|------------:|:--------|:------------|
|  0 | cash_ratio     |  0.710813  |  4.87448  | 1.09093e-06 | ***     | positive    |
|  1 | asset_growth   | -0.173115  | -2.05163  | 0.0402054   | **      | negative    |
|  2 | debt_ratio     | -0.218856  | -0.859097 | 0.390287    |         | negative    |
|  3 | market_to_book | -0.0596075 | -2.13771  | 0.0325403   | **      | negative    |
|  4 | equity_ratio   |  0.360657  |  1.05929  | 0.289467    |         | positive    |
|  5 | roa            |  3.28135   |  1.72792  | 0.0840026   | *       | positive    |
|  6 | size           | -0.0154682 | -2.29299  | 0.0218487   | **      | negative    |

========================
13. TASK FOR CHATGPT
========================

Please interpret these PERMCO-based results for my meeting with the professor.
Focus on:
1. whether the PERMCO-based sample construction worked,
2. whether the main liquidity / asset growth / market-to-book results are consistent with the earlier analysis,
3. whether the results are strong enough to discuss with the professor,
4. what tables I should bring to the meeting,
5. what weaknesses or caveats I should mention,
6. what next empirical step I should take.


Saved copy-paste report to:
C:\Users\starw\OneDrive\바탕 화면\학교 생활\UNIST\Research\박지훈 자료\permco_bank_analysis_output\28_COPY_THIS_TO_CHATGPT.txt